# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pict

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 517)
        self.centralWidget_SP = QtWidgets.QWidget(MainWindow)
        self.centralWidget_SP.setObjectName("centralWidget_SP")
        self.stackedWidget_SP = QtWidgets.QStackedWidget(self.centralWidget_SP)
        self.stackedWidget_SP.setGeometry(QtCore.QRect(10, 0, 631, 461))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget_SP.setFont(font)
        self.stackedWidget_SP.setObjectName("stackedWidget_SP")
        self.pageLogin = QtWidgets.QWidget()
        self.pageLogin.setObjectName("pageLogin")
        self.groupBox_Logining = QtWidgets.QGroupBox(self.pageLogin)
        self.groupBox_Logining.setGeometry(QtCore.QRect(10, 10, 611, 441))
        self.groupBox_Logining.setObjectName("groupBox_Logining")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox_Logining)
        self.buttonBox.setGeometry(QtCore.QRect(240, 380, 156, 31))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEditLogin = QtWidgets.QLineEdit(self.groupBox_Logining)
        self.lineEditLogin.setGeometry(QtCore.QRect(320, 270, 113, 20))
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.lineEditPassword = QtWidgets.QLineEdit(self.groupBox_Logining)
        self.lineEditPassword.setGeometry(QtCore.QRect(320, 310, 113, 20))
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.labelPicture = QtWidgets.QLabel(self.groupBox_Logining)
        self.labelPicture.setGeometry(QtCore.QRect(10, 30, 591, 221))
        self.labelPicture.setText("")
        self.labelPicture.setPixmap(QtGui.QPixmap(":/stiftung_gross_03.jpg"))
        self.labelPicture.setObjectName("labelPicture")
        self.labelLogining = QtWidgets.QLabel(self.groupBox_Logining)
        self.labelLogining.setGeometry(QtCore.QRect(240, 270, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelLogining.setFont(font)
        self.labelLogining.setObjectName("labelLogining")
        self.labelPassword = QtWidgets.QLabel(self.groupBox_Logining)
        self.labelPassword.setGeometry(QtCore.QRect(220, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelPassword.setFont(font)
        self.labelPassword.setObjectName("labelPassword")
        self.stackedWidget_SP.addWidget(self.pageLogin)
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page_main)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 601, 451))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_main = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_main.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_main.setSpacing(6)
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.pushButton_Main_Spare_Parts = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Main_Spare_Parts.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Main_Spare_Parts.setIcon(icon)
        self.pushButton_Main_Spare_Parts.setIconSize(QtCore.QSize(300, 100))
        self.pushButton_Main_Spare_Parts.setObjectName("pushButton_Main_Spare_Parts")
        self.gridLayout_main.addWidget(self.pushButton_Main_Spare_Parts, 0, 0, 1, 1)
        self.pushButton_Main_Report = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Main_Report.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/20160205companypresentationprettlgroupen-3-638.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Main_Report.setIcon(icon1)
        self.pushButton_Main_Report.setIconSize(QtCore.QSize(300, 100))
        self.pushButton_Main_Report.setObjectName("pushButton_Main_Report")
        self.gridLayout_main.addWidget(self.pushButton_Main_Report, 1, 0, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_main)
        self.pageMain = QtWidgets.QWidget()
        self.pageMain.setObjectName("pageMain")
        self.gridLayoutWidget = QtWidgets.QWidget(self.pageMain)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 621, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonInput = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonInput.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/AGCO-Parts-Box-2-2-1214x1280-971x1024.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonInput.setIcon(icon2)
        self.pushButtonInput.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonInput.setObjectName("pushButtonInput")
        self.gridLayout.addWidget(self.pushButtonInput, 1, 0, 1, 1)
        self.pushButtonStok = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStok.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Schermata-2017-06-27-alle-17.36.44-495x400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStok.setIcon(icon3)
        self.pushButtonStok.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonStok.setObjectName("pushButtonStok")
        self.gridLayout.addWidget(self.pushButtonStok, 2, 0, 1, 1)
        self.pushButtonEquipment = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEquipment.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Без названия.jfif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEquipment.setIcon(icon4)
        self.pushButtonEquipment.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonEquipment.setObjectName("pushButtonEquipment")
        self.gridLayout.addWidget(self.pushButtonEquipment, 0, 1, 1, 1)
        self.pushButtonEngeneer = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEngeneer.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Komax_Academy_216x160.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEngeneer.setIcon(icon5)
        self.pushButtonEngeneer.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonEngeneer.setObjectName("pushButtonEngeneer")
        self.gridLayout.addWidget(self.pushButtonEngeneer, 1, 1, 1, 1)
        self.pushButtonOperator = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOperator.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/992593_cms2image-fixedwidth-640x0_1ovuKH_TgrNff.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOperator.setIcon(icon6)
        self.pushButtonOperator.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonOperator.setObjectName("pushButtonOperator")
        self.gridLayout.addWidget(self.pushButtonOperator, 2, 1, 1, 1)
        self.pushButtonParts = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonParts.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/stock-photo-new-auto-spare-parts-around-clutch-disc-isolated-on-white-background-360630473.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonParts.setIcon(icon7)
        self.pushButtonParts.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonParts.setObjectName("pushButtonParts")
        self.gridLayout.addWidget(self.pushButtonParts, 0, 0, 1, 1)
        self.stackedWidget_SP.addWidget(self.pageMain)
        self.page_Incoming = QtWidgets.QWidget()
        self.page_Incoming.setObjectName("page_Incoming")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.page_Incoming)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 0, 611, 461))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_Incoming = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_Incoming.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_Incoming.setSpacing(6)
        self.gridLayout_Incoming.setObjectName("gridLayout_Incoming")
        self.lineEdit_Incoming_SPN = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Incoming_SPN.setObjectName("lineEdit_Incoming_SPN")
        self.gridLayout_Incoming.addWidget(self.lineEdit_Incoming_SPN, 2, 0, 1, 1)
        self.label_SPN = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_SPN.setFont(font)
        self.label_SPN.setScaledContents(True)
        self.label_SPN.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SPN.setObjectName("label_SPN")
        self.gridLayout_Incoming.addWidget(self.label_SPN, 0, 0, 1, 1)
        self.buttonBox_Incoming = QtWidgets.QDialogButtonBox(self.gridLayoutWidget_4)
        self.buttonBox_Incoming.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Incoming.setObjectName("buttonBox_Incoming")
        self.gridLayout_Incoming.addWidget(self.buttonBox_Incoming, 9, 3, 1, 1)
        self.label_DPN = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_DPN.setFont(font)
        self.label_DPN.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DPN.setObjectName("label_DPN")
        self.gridLayout_Incoming.addWidget(self.label_DPN, 0, 1, 1, 1)
        self.lineEdit_DPN = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_DPN.setObjectName("lineEdit_DPN")
        self.gridLayout_Incoming.addWidget(self.lineEdit_DPN, 2, 1, 1, 1)
        self.label_Store_place = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Store_place.setFont(font)
        self.label_Store_place.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Store_place.setObjectName("label_Store_place")
        self.gridLayout_Incoming.addWidget(self.label_Store_place, 4, 3, 1, 1)
        self.lineEdit_Store_place = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Store_place.setObjectName("lineEdit_Store_place")
        self.gridLayout_Incoming.addWidget(self.lineEdit_Store_place, 5, 3, 1, 1)
        self.label_QTY = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_QTY.setFont(font)
        self.label_QTY.setAlignment(QtCore.Qt.AlignCenter)
        self.label_QTY.setObjectName("label_QTY")
        self.gridLayout_Incoming.addWidget(self.label_QTY, 4, 0, 1, 1)
        self.lineEdit_QTY = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_QTY.setObjectName("lineEdit_QTY")
        self.gridLayout_Incoming.addWidget(self.lineEdit_QTY, 5, 0, 1, 1)
        self.label_Description = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Description.setFont(font)
        self.label_Description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Description.setObjectName("label_Description")
        self.gridLayout_Incoming.addWidget(self.label_Description, 6, 0, 1, 1)
        self.lineEdit_Description = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Description.setObjectName("lineEdit_Description")
        self.gridLayout_Incoming.addWidget(self.lineEdit_Description, 8, 0, 1, 1)
        self.label_Invoice_Number = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Invoice_Number.setFont(font)
        self.label_Invoice_Number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Invoice_Number.setObjectName("label_Invoice_Number")
        self.gridLayout_Incoming.addWidget(self.label_Invoice_Number, 0, 3, 1, 1)
        self.lineEdit_Invoice_Number = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Invoice_Number.setObjectName("lineEdit_Invoice_Number")
        self.gridLayout_Incoming.addWidget(self.lineEdit_Invoice_Number, 2, 3, 1, 1)
        self.lineEdit_Date_Order = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Date_Order.setObjectName("lineEdit_Date_Order")
        self.gridLayout_Incoming.addWidget(self.lineEdit_Date_Order, 8, 1, 1, 1)
        self.label_Date_Incoming = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Date_Incoming.setFont(font)
        self.label_Date_Incoming.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Date_Incoming.setObjectName("label_Date_Incoming")
        self.gridLayout_Incoming.addWidget(self.label_Date_Incoming, 6, 3, 1, 1)
        self.lineEdit_Date_Incoming = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Date_Incoming.setObjectName("lineEdit_Date_Incoming")
        self.gridLayout_Incoming.addWidget(self.lineEdit_Date_Incoming, 8, 3, 1, 1)
        self.label_Date_Order = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Date_Order.setFont(font)
        self.label_Date_Order.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Date_Order.setObjectName("label_Date_Order")
        self.gridLayout_Incoming.addWidget(self.label_Date_Order, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label.setMaximumSize(QtCore.QSize(200, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/AGCO-Parts-Box-2-2-1214x1280-971x1024.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_Incoming.addWidget(self.label, 9, 1, 1, 1)
        self.lineEdit_Price = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_Price.setObjectName("lineEdit_Price")
        self.gridLayout_Incoming.addWidget(self.lineEdit_Price, 5, 1, 1, 1)
        self.label_Price = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Price.setFont(font)
        self.label_Price.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Price.setObjectName("label_Price")
        self.gridLayout_Incoming.addWidget(self.label_Price, 4, 1, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_Incoming)
        self.page_Parts = QtWidgets.QWidget()
        self.page_Parts.setObjectName("page_Parts")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.page_Parts)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 10, 621, 171))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_Parts = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_Parts.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_Parts.setSpacing(6)
        self.gridLayout_Parts.setObjectName("gridLayout_Parts")
        self.lineEdit_Parts_DPN = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_Parts_DPN.setObjectName("lineEdit_Parts_DPN")
        self.gridLayout_Parts.addWidget(self.lineEdit_Parts_DPN, 1, 0, 1, 1)
        self.radioButton_Parts_MQB2 = QtWidgets.QRadioButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Parts_MQB2.setFont(font)
        self.radioButton_Parts_MQB2.setObjectName("radioButton_Parts_MQB2")
        self.gridLayout_Parts.addWidget(self.radioButton_Parts_MQB2, 2, 1, 1, 1)
        self.lineEdit_SAP_NUMBER = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_SAP_NUMBER.setObjectName("lineEdit_SAP_NUMBER")
        self.gridLayout_Parts.addWidget(self.lineEdit_SAP_NUMBER, 1, 1, 1, 1)
        self.radioButton_Parts_MQB1 = QtWidgets.QRadioButton(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Parts_MQB1.setFont(font)
        self.radioButton_Parts_MQB1.setObjectName("radioButton_Parts_MQB1")
        self.gridLayout_Parts.addWidget(self.radioButton_Parts_MQB1, 2, 0, 1, 1)
        self.comboBox_Parts_Project = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.comboBox_Parts_Project.setObjectName("comboBox_Parts_Project")
        self.gridLayout_Parts.addWidget(self.comboBox_Parts_Project, 1, 2, 1, 1)
        self.buttonBox_Parts = QtWidgets.QDialogButtonBox(self.gridLayoutWidget_5)
        self.buttonBox_Parts.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Parts.setObjectName("buttonBox_Parts")
        self.gridLayout_Parts.addWidget(self.buttonBox_Parts, 2, 2, 1, 1)
        self.label_Parts_DPN = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Parts_DPN.setFont(font)
        self.label_Parts_DPN.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Parts_DPN.setObjectName("label_Parts_DPN")
        self.gridLayout_Parts.addWidget(self.label_Parts_DPN, 0, 0, 1, 1)
        self.label_Parts_Projects = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Parts_Projects.setFont(font)
        self.label_Parts_Projects.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Parts_Projects.setObjectName("label_Parts_Projects")
        self.gridLayout_Parts.addWidget(self.label_Parts_Projects, 0, 2, 1, 1)
        self.label_SAP_NUMBER = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_SAP_NUMBER.setFont(font)
        self.label_SAP_NUMBER.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SAP_NUMBER.setObjectName("label_SAP_NUMBER")
        self.gridLayout_Parts.addWidget(self.label_SAP_NUMBER, 0, 1, 1, 1)
        self.tableView_Parts = QtWidgets.QTableView(self.page_Parts)
        self.tableView_Parts.setGeometry(QtCore.QRect(0, 180, 621, 261))
        self.tableView_Parts.setObjectName("tableView_Parts")
        self.stackedWidget_SP.addWidget(self.page_Parts)
        self.page_EQIUPMENT = QtWidgets.QWidget()
        self.page_EQIUPMENT.setObjectName("page_EQIUPMENT")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.page_EQIUPMENT)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 611, 431))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_EQIUPMENT = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_EQIUPMENT.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_EQIUPMENT.setSpacing(6)
        self.gridLayout_EQIUPMENT.setObjectName("gridLayout_EQIUPMENT")
        self.buttonBox_EQIUPMENT = QtWidgets.QDialogButtonBox(self.gridLayoutWidget_6)
        self.buttonBox_EQIUPMENT.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_EQIUPMENT.setObjectName("buttonBox_EQIUPMENT")
        self.gridLayout_EQIUPMENT.addWidget(self.buttonBox_EQIUPMENT, 3, 2, 1, 1)
        self.lineEdit_QS_Number = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_QS_Number.setObjectName("lineEdit_QS_Number")
        self.gridLayout_EQIUPMENT.addWidget(self.lineEdit_QS_Number, 1, 2, 1, 1)
        self.lineEdit_Serial_number = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_Serial_number.setObjectName("lineEdit_Serial_number")
        self.gridLayout_EQIUPMENT.addWidget(self.lineEdit_Serial_number, 1, 1, 1, 1)
        self.lineEdit_EQP_Description = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_EQP_Description.setObjectName("lineEdit_EQP_Description")
        self.gridLayout_EQIUPMENT.addWidget(self.lineEdit_EQP_Description, 1, 0, 1, 1)
        self.label_Serial_number = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Serial_number.setFont(font)
        self.label_Serial_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Serial_number.setObjectName("label_Serial_number")
        self.gridLayout_EQIUPMENT.addWidget(self.label_Serial_number, 0, 1, 1, 1)
        self.label_QS_Number = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_QS_Number.setFont(font)
        self.label_QS_Number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_QS_Number.setObjectName("label_QS_Number")
        self.gridLayout_EQIUPMENT.addWidget(self.label_QS_Number, 0, 2, 1, 1)
        self.label_EQP_Description = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_EQP_Description.setFont(font)
        self.label_EQP_Description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_EQP_Description.setObjectName("label_EQP_Description")
        self.gridLayout_EQIUPMENT.addWidget(self.label_EQP_Description, 0, 0, 1, 1)
        self.label_EQIUPMENT_picture = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_EQIUPMENT_picture.setMaximumSize(QtCore.QSize(200, 150))
        self.label_EQIUPMENT_picture.setText("")
        self.label_EQIUPMENT_picture.setPixmap(QtGui.QPixmap(":/Без названия.jfif"))
        self.label_EQIUPMENT_picture.setScaledContents(True)
        self.label_EQIUPMENT_picture.setObjectName("label_EQIUPMENT_picture")
        self.gridLayout_EQIUPMENT.addWidget(self.label_EQIUPMENT_picture, 2, 1, 1, 1)
        self.radioButton_EQIUPMENT_MQB1 = QtWidgets.QRadioButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_EQIUPMENT_MQB1.setFont(font)
        self.radioButton_EQIUPMENT_MQB1.setObjectName("radioButton_EQIUPMENT_MQB1")
        self.gridLayout_EQIUPMENT.addWidget(self.radioButton_EQIUPMENT_MQB1, 2, 0, 1, 1)
        self.radioButton_EQIUPMENT_MQB2 = QtWidgets.QRadioButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_EQIUPMENT_MQB2.setFont(font)
        self.radioButton_EQIUPMENT_MQB2.setObjectName("radioButton_EQIUPMENT_MQB2")
        self.gridLayout_EQIUPMENT.addWidget(self.radioButton_EQIUPMENT_MQB2, 2, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_EQIUPMENT)
        self.page_maintenance = QtWidgets.QWidget()
        self.page_maintenance.setObjectName("page_maintenance")
        self.label_maintenance_Name = QtWidgets.QLabel(self.page_maintenance)
        self.label_maintenance_Name.setGeometry(QtCore.QRect(20, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_maintenance_Name.setFont(font)
        self.label_maintenance_Name.setObjectName("label_maintenance_Name")
        self.label_maintenance_Tab_Numer = QtWidgets.QLabel(self.page_maintenance)
        self.label_maintenance_Tab_Numer.setGeometry(QtCore.QRect(20, 110, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_maintenance_Tab_Numer.setFont(font)
        self.label_maintenance_Tab_Numer.setObjectName("label_maintenance_Tab_Numer")
        self.label_maintenance_Area = QtWidgets.QLabel(self.page_maintenance)
        self.label_maintenance_Area.setGeometry(QtCore.QRect(20, 160, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_maintenance_Area.setFont(font)
        self.label_maintenance_Area.setObjectName("label_maintenance_Area")
        self.ButtomBox_maintenance = QtWidgets.QDialogButtonBox(self.page_maintenance)
        self.ButtomBox_maintenance.setGeometry(QtCore.QRect(430, 420, 161, 31))
        self.ButtomBox_maintenance.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ButtomBox_maintenance.setObjectName("ButtomBox_maintenance")
        self.lineEdit_maintenance_Name = QtWidgets.QLineEdit(self.page_maintenance)
        self.lineEdit_maintenance_Name.setGeometry(QtCore.QRect(20, 80, 131, 20))
        self.lineEdit_maintenance_Name.setObjectName("lineEdit_maintenance_Name")
        self.lineEdit_maintenance_Tab_Number = QtWidgets.QLineEdit(self.page_maintenance)
        self.lineEdit_maintenance_Tab_Number.setGeometry(QtCore.QRect(20, 140, 131, 20))
        self.lineEdit_maintenance_Tab_Number.setObjectName("lineEdit_maintenance_Tab_Number")
        self.lineEdit_maintenance_Area = QtWidgets.QLineEdit(self.page_maintenance)
        self.lineEdit_maintenance_Area.setGeometry(QtCore.QRect(20, 190, 131, 20))
        self.lineEdit_maintenance_Area.setObjectName("lineEdit_maintenance_Area")
        self.label_Maintenance_picture = QtWidgets.QLabel(self.page_maintenance)
        self.label_Maintenance_picture.setGeometry(QtCore.QRect(20, 240, 221, 171))
        self.label_Maintenance_picture.setMaximumSize(QtCore.QSize(400, 400))
        self.label_Maintenance_picture.setText("")
        self.label_Maintenance_picture.setPixmap(QtGui.QPixmap(":/Komax_Academy_216x160.jpg"))
        self.label_Maintenance_picture.setObjectName("label_Maintenance_picture")
        self.tableView_Maintenance = QtWidgets.QTableView(self.page_maintenance)
        self.tableView_Maintenance.setGeometry(QtCore.QRect(250, 20, 361, 391))
        self.tableView_Maintenance.setObjectName("tableView_Maintenance")
        self.stackedWidget_SP.addWidget(self.page_maintenance)
        self.page_operators = QtWidgets.QWidget()
        self.page_operators.setObjectName("page_operators")
        self.label_operators_Name = QtWidgets.QLabel(self.page_operators)
        self.label_operators_Name.setGeometry(QtCore.QRect(50, 40, 71, 21))
        self.label_operators_Name.setObjectName("label_operators_Name")
        self.lineEdit_operators_Name = QtWidgets.QLineEdit(self.page_operators)
        self.lineEdit_operators_Name.setGeometry(QtCore.QRect(50, 70, 141, 20))
        self.lineEdit_operators_Name.setObjectName("lineEdit_operators_Name")
        self.label_operators_Tab_Number = QtWidgets.QLabel(self.page_operators)
        self.label_operators_Tab_Number.setGeometry(QtCore.QRect(50, 110, 131, 21))
        self.label_operators_Tab_Number.setObjectName("label_operators_Tab_Number")
        self.label_operators_Team = QtWidgets.QLabel(self.page_operators)
        self.label_operators_Team.setGeometry(QtCore.QRect(50, 175, 111, 21))
        self.label_operators_Team.setObjectName("label_operators_Team")
        self.lineEdit_operators_Team = QtWidgets.QLineEdit(self.page_operators)
        self.lineEdit_operators_Team.setGeometry(QtCore.QRect(50, 200, 141, 20))
        self.lineEdit_operators_Team.setObjectName("lineEdit_operators_Team")
        self.lineEdit_operators_Tab_Number = QtWidgets.QLineEdit(self.page_operators)
        self.lineEdit_operators_Tab_Number.setGeometry(QtCore.QRect(50, 138, 141, 20))
        self.lineEdit_operators_Tab_Number.setObjectName("lineEdit_operators_Tab_Number")
        self.buttonBox_Operators = QtWidgets.QDialogButtonBox(self.page_operators)
        self.buttonBox_Operators.setGeometry(QtCore.QRect(450, 420, 156, 23))
        self.buttonBox_Operators.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Operators.setObjectName("buttonBox_Operators")
        self.label_Operator_Picture = QtWidgets.QLabel(self.page_operators)
        self.label_Operator_Picture.setGeometry(QtCore.QRect(30, 230, 221, 171))
        self.label_Operator_Picture.setMaximumSize(QtCore.QSize(400, 400))
        self.label_Operator_Picture.setText("")
        self.label_Operator_Picture.setPixmap(QtGui.QPixmap(":/992593_cms2image-fixedwidth-640x0_1ovuKH_TgrNff.jpg"))
        self.label_Operator_Picture.setScaledContents(True)
        self.label_Operator_Picture.setObjectName("label_Operator_Picture")
        self.tableWidget_Operators = QtWidgets.QTableWidget(self.page_operators)
        self.tableWidget_Operators.setGeometry(QtCore.QRect(270, 40, 351, 371))
        self.tableWidget_Operators.setObjectName("tableWidget_Operators")
        self.tableWidget_Operators.setColumnCount(0)
        self.tableWidget_Operators.setRowCount(0)
        self.stackedWidget_SP.addWidget(self.page_operators)
        self.page_output = QtWidgets.QWidget()
        self.page_output.setObjectName("page_output")
        self.label_output_Equipment = QtWidgets.QLabel(self.page_output)
        self.label_output_Equipment.setGeometry(QtCore.QRect(60, 80, 121, 21))
        self.label_output_Equipment.setObjectName("label_output_Equipment")
        self.radioButton_Output_MQB1 = QtWidgets.QRadioButton(self.page_output)
        self.radioButton_Output_MQB1.setGeometry(QtCore.QRect(60, 20, 101, 17))
        self.radioButton_Output_MQB1.setObjectName("radioButton_Output_MQB1")
        self.radioButton_Output_MQB2 = QtWidgets.QRadioButton(self.page_output)
        self.radioButton_Output_MQB2.setGeometry(QtCore.QRect(60, 50, 101, 17))
        self.radioButton_Output_MQB2.setObjectName("radioButton_Output_MQB2")
        self.comboBox_Output_Equipment = QtWidgets.QComboBox(self.page_output)
        self.comboBox_Output_Equipment.setGeometry(QtCore.QRect(60, 110, 191, 22))
        self.comboBox_Output_Equipment.setObjectName("comboBox_Output_Equipment")
        self.label_Output_Date = QtWidgets.QLabel(self.page_output)
        self.label_Output_Date.setGeometry(QtCore.QRect(180, 20, 61, 21))
        self.label_Output_Date.setObjectName("label_Output_Date")
        self.label_Output_DPN = QtWidgets.QLabel(self.page_output)
        self.label_Output_DPN.setGeometry(QtCore.QRect(60, 140, 51, 21))
        self.label_Output_DPN.setObjectName("label_Output_DPN")
        self.comboBox_Output_DPN = QtWidgets.QComboBox(self.page_output)
        self.comboBox_Output_DPN.setGeometry(QtCore.QRect(60, 170, 191, 22))
        self.comboBox_Output_DPN.setObjectName("comboBox_Output_DPN")
        self.label_Output_maintenance = QtWidgets.QLabel(self.page_output)
        self.label_Output_maintenance.setGeometry(QtCore.QRect(60, 200, 211, 21))
        self.label_Output_maintenance.setObjectName("label_Output_maintenance")
        self.comboBox_Output_maintanance = QtWidgets.QComboBox(self.page_output)
        self.comboBox_Output_maintanance.setGeometry(QtCore.QRect(60, 230, 191, 22))
        self.comboBox_Output_maintanance.setObjectName("comboBox_Output_maintanance")
        self.buttonBox_3 = QtWidgets.QDialogButtonBox(self.page_output)
        self.buttonBox_3.setGeometry(QtCore.QRect(450, 420, 156, 23))
        self.buttonBox_3.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_3.setObjectName("buttonBox_3")
        self.label_Output_picture = QtWidgets.QLabel(self.page_output)
        self.label_Output_picture.setGeometry(QtCore.QRect(60, 380, 101, 51))
        self.label_Output_picture.setText("")
        self.label_Output_picture.setPixmap(QtGui.QPixmap(":/Schermata-2017-06-27-alle-17.36.44-495x400.png"))
        self.label_Output_picture.setScaledContents(True)
        self.label_Output_picture.setObjectName("label_Output_picture")
        self.tableView_Output = QtWidgets.QTableView(self.page_output)
        self.tableView_Output.setGeometry(QtCore.QRect(270, 20, 361, 381))
        self.tableView_Output.setObjectName("tableView_Output")
        self.comboBox_Output_Reason = QtWidgets.QComboBox(self.page_output)
        self.comboBox_Output_Reason.setGeometry(QtCore.QRect(60, 290, 191, 22))
        self.comboBox_Output_Reason.setObjectName("comboBox_Output_Reason")
        self.label_Output_Reason = QtWidgets.QLabel(self.page_output)
        self.label_Output_Reason.setGeometry(QtCore.QRect(60, 260, 211, 21))
        self.label_Output_Reason.setObjectName("label_Output_Reason")
        self.label_Output_QTY = QtWidgets.QLabel(self.page_output)
        self.label_Output_QTY.setGeometry(QtCore.QRect(60, 320, 191, 21))
        self.label_Output_QTY.setObjectName("label_Output_QTY")
        self.lineEdit_Output_QTY = QtWidgets.QLineEdit(self.page_output)
        self.lineEdit_Output_QTY.setGeometry(QtCore.QRect(60, 350, 191, 20))
        self.lineEdit_Output_QTY.setObjectName("lineEdit_Output_QTY")
        self.stackedWidget_SP.addWidget(self.page_output)
        self.pageReports = QtWidgets.QWidget()
        self.pageReports.setObjectName("pageReports")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.pageReports)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 621, 451))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonDailyReport = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDailyReport.setFont(font)
        self.pushButtonDailyReport.setObjectName("pushButtonDailyReport")
        self.gridLayout_2.addWidget(self.pushButtonDailyReport, 1, 0, 1, 1)
        self.pushButtonPartsEmploeeReport = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPartsEmploeeReport.setFont(font)
        self.pushButtonPartsEmploeeReport.setObjectName("pushButtonPartsEmploeeReport")
        self.gridLayout_2.addWidget(self.pushButtonPartsEmploeeReport, 0, 1, 1, 1)
        self.pushButtonOrderReport = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOrderReport.setFont(font)
        self.pushButtonOrderReport.setObjectName("pushButtonOrderReport")
        self.gridLayout_2.addWidget(self.pushButtonOrderReport, 2, 0, 1, 1)
        self.pushButtonStockReport = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStockReport.setFont(font)
        self.pushButtonStockReport.setObjectName("pushButtonStockReport")
        self.gridLayout_2.addWidget(self.pushButtonStockReport, 0, 0, 1, 1)
        self.pushButtonPartsMachineReport = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPartsMachineReport.setFont(font)
        self.pushButtonPartsMachineReport.setObjectName("pushButtonPartsMachineReport")
        self.gridLayout_2.addWidget(self.pushButtonPartsMachineReport, 3, 0, 1, 1)
        self.pushButtonMounthlyStockCutting = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonMounthlyStockCutting.setFont(font)
        self.pushButtonMounthlyStockCutting.setObjectName("pushButtonMounthlyStockCutting")
        self.gridLayout_2.addWidget(self.pushButtonMounthlyStockCutting, 1, 1, 1, 1)
        self.pushButtonMounthlyStockProduction = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonMounthlyStockProduction.setFont(font)
        self.pushButtonMounthlyStockProduction.setObjectName("pushButtonMounthlyStockProduction")
        self.gridLayout_2.addWidget(self.pushButtonMounthlyStockProduction, 2, 1, 1, 1)
        self.pushButtonTimeLifeSP = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTimeLifeSP.setFont(font)
        self.pushButtonTimeLifeSP.setObjectName("pushButtonTimeLifeSP")
        self.gridLayout_2.addWidget(self.pushButtonTimeLifeSP, 3, 1, 1, 1)
        self.stackedWidget_SP.addWidget(self.pageReports)
        MainWindow.setCentralWidget(self.centralWidget_SP)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 646, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_SP.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_Logining.setTitle(_translate("MainWindow", "Spare Parts"))
        self.labelLogining.setText(_translate("MainWindow", "Login"))
        self.labelPassword.setText(_translate("MainWindow", "Password"))
        self.pushButton_Main_Spare_Parts.setText(_translate("MainWindow", "SPARE PARTS"))
        self.pushButton_Main_Report.setText(_translate("MainWindow", "REPORTS"))
        self.pushButtonInput.setText(_translate("MainWindow", "           Прихід"))
        self.pushButtonStok.setText(_translate("MainWindow", "      Списання"))
        self.pushButtonEquipment.setText(_translate("MainWindow", "         Обладнання"))
        self.pushButtonEngeneer.setText(_translate("MainWindow", "Налагоджувальник"))
        self.pushButtonOperator.setText(_translate("MainWindow", "                Оператор"))
        self.pushButtonParts.setText(_translate("MainWindow", "            Деталі"))
        self.label_SPN.setText(_translate("MainWindow", "SPN"))
        self.label_DPN.setText(_translate("MainWindow", "DPN"))
        self.label_Store_place.setText(_translate("MainWindow", "Store Place"))
        self.label_QTY.setText(_translate("MainWindow", "QTY"))
        self.label_Description.setText(_translate("MainWindow", "Description"))
        self.label_Invoice_Number.setText(_translate("MainWindow", "Invoice Number"))
        self.label_Date_Incoming.setText(_translate("MainWindow", "Date Incoming"))
        self.label_Date_Order.setText(_translate("MainWindow", "Date Order"))
        self.label_Price.setText(_translate("MainWindow", "Price"))
        self.radioButton_Parts_MQB2.setText(_translate("MainWindow", "MQB2"))
        self.radioButton_Parts_MQB1.setText(_translate("MainWindow", "MQB1"))
        self.label_Parts_DPN.setText(_translate("MainWindow", "DPN"))
        self.label_Parts_Projects.setText(_translate("MainWindow", "PROJECT"))
        self.label_SAP_NUMBER.setText(_translate("MainWindow", "SAP NUMBER"))
        self.label_Serial_number.setText(_translate("MainWindow", "Serial Number"))
        self.label_QS_Number.setText(_translate("MainWindow", "QS Number"))
        self.label_EQP_Description.setText(_translate("MainWindow", "EQP Description"))
        self.radioButton_EQIUPMENT_MQB1.setText(_translate("MainWindow", "MQB1"))
        self.radioButton_EQIUPMENT_MQB2.setText(_translate("MainWindow", "MQB2"))
        self.label_maintenance_Name.setText(_translate("MainWindow", "Name"))
        self.label_maintenance_Tab_Numer.setText(_translate("MainWindow", "Tab number"))
        self.label_maintenance_Area.setText(_translate("MainWindow", "Area"))
        self.label_operators_Name.setText(_translate("MainWindow", "Name"))
        self.label_operators_Tab_Number.setText(_translate("MainWindow", "Tab Number"))
        self.label_operators_Team.setText(_translate("MainWindow", "Team"))
        self.label_output_Equipment.setText(_translate("MainWindow", "Equipment"))
        self.radioButton_Output_MQB1.setText(_translate("MainWindow", "MQB 1"))
        self.radioButton_Output_MQB2.setText(_translate("MainWindow", "MQB 2"))
        self.label_Output_Date.setText(_translate("MainWindow", "Date"))
        self.label_Output_DPN.setText(_translate("MainWindow", "DPN"))
        self.label_Output_maintenance.setText(_translate("MainWindow", "Maintenance name"))
        self.label_Output_Reason.setText(_translate("MainWindow", "Reason"))
        self.label_Output_QTY.setText(_translate("MainWindow", "QTY"))
        self.pushButtonDailyReport.setText(_translate("MainWindow", "Щоденний"))
        self.pushButtonPartsEmploeeReport.setText(_translate("MainWindow", "Запчастини/Людина"))
        self.pushButtonOrderReport.setText(_translate("MainWindow", "Замовлення"))
        self.pushButtonStockReport.setText(_translate("MainWindow", "STOCK"))
        self.pushButtonPartsMachineReport.setText(_translate("MainWindow", "Запчастини/Машина"))
        self.pushButtonMounthlyStockCutting.setText(_translate("MainWindow", "Місячне Списання Різка"))
        self.pushButtonMounthlyStockProduction.setText(_translate("MainWindow", "Місячне Списання Виробництво"))
        self.pushButtonTimeLifeSP.setText(_translate("MainWindow", "Цикл роботи/використання SP"))

import res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

