# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1109, 925)
        self.centralWidget_SP = QtWidgets.QWidget(MainWindow)
        self.centralWidget_SP.setObjectName("centralWidget_SP")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget_SP)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget_SP = QtWidgets.QStackedWidget(self.centralWidget_SP)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget_SP.setFont(font)
        self.stackedWidget_SP.setObjectName("stackedWidget_SP")
        self.pageLogin = QtWidgets.QWidget()
        self.pageLogin.setObjectName("pageLogin")
        self.groupBox_Logining = QtWidgets.QGroupBox(self.pageLogin)
        self.groupBox_Logining.setGeometry(QtCore.QRect(10, 10, 1061, 791))
        self.groupBox_Logining.setObjectName("groupBox_Logining")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_Logining)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.labelLogining = QtWidgets.QLabel(self.groupBox_Logining)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelLogining.setFont(font)
        self.labelLogining.setObjectName("labelLogining")
        self.gridLayout_5.addWidget(self.labelLogining, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 3, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(self.groupBox_Logining)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setCursorPosition(0)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout_5.addWidget(self.lineEditPassword, 2, 2, 1, 1)
        self.labelPassword = QtWidgets.QLabel(self.groupBox_Logining)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelPassword.setFont(font)
        self.labelPassword.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.labelPassword.setMouseTracking(False)
        self.labelPassword.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelPassword.setMidLineWidth(0)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout_5.addWidget(self.labelPassword, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox_Logining)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_5.addWidget(self.buttonBox, 3, 1, 1, 2)
        self.lineEditLogin = QtWidgets.QLineEdit(self.groupBox_Logining)
        self.lineEditLogin.setTabletTracking(False)
        self.lineEditLogin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditLogin.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditLogin.setCursorPosition(0)
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.gridLayout_5.addWidget(self.lineEditLogin, 1, 2, 1, 1)
        self.labelPicture = QtWidgets.QLabel(self.groupBox_Logining)
        self.labelPicture.setText("")
        self.labelPicture.setPixmap(QtGui.QPixmap(":/res/imgonline-com-ua-Transparent-backgr-iB6yDNbb6OyTox.png"))
        self.labelPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPicture.setWordWrap(False)
        self.labelPicture.setObjectName("labelPicture")
        self.gridLayout_5.addWidget(self.labelPicture, 0, 0, 1, 4)
        self.stackedWidget_SP.addWidget(self.pageLogin)
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_main)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_Main_Spare_Parts = QtWidgets.QPushButton(self.page_main)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Main_Spare_Parts.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/res/tools.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_Main_Spare_Parts.setIcon(icon)
        self.pushButton_Main_Spare_Parts.setIconSize(QtCore.QSize(300, 100))
        self.pushButton_Main_Spare_Parts.setObjectName("pushButton_Main_Spare_Parts")
        self.gridLayout_3.addWidget(self.pushButton_Main_Spare_Parts, 0, 0, 1, 1)
        self.pushButton_Main_Report = QtWidgets.QPushButton(self.page_main)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Main_Report.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/20160205companypresentationprettlgroupen-3-638.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/res/20160205companypresentationprettlgroupen-3-638.jpg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_Main_Report.setIcon(icon1)
        self.pushButton_Main_Report.setIconSize(QtCore.QSize(300, 100))
        self.pushButton_Main_Report.setObjectName("pushButton_Main_Report")
        self.gridLayout_3.addWidget(self.pushButton_Main_Report, 1, 0, 1, 1)
        self.pushButton_Crimping_Die = QtWidgets.QPushButton(self.page_main)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/26733-2727347.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Crimping_Die.setIcon(icon2)
        self.pushButton_Crimping_Die.setIconSize(QtCore.QSize(200, 100))
        self.pushButton_Crimping_Die.setObjectName("pushButton_Crimping_Die")
        self.gridLayout_3.addWidget(self.pushButton_Crimping_Die, 2, 0, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_main)
        self.page_Crimping_Select = QtWidgets.QWidget()
        self.page_Crimping_Select.setObjectName("page_Crimping_Select")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_Crimping_Select)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_Crimping_Select_Tool = QtWidgets.QPushButton(self.page_Crimping_Select)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/41nLbUHoArL.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Crimping_Select_Tool.setIcon(icon3)
        self.pushButton_Crimping_Select_Tool.setIconSize(QtCore.QSize(200, 100))
        self.pushButton_Crimping_Select_Tool.setObjectName("pushButton_Crimping_Select_Tool")
        self.gridLayout_6.addWidget(self.pushButton_Crimping_Select_Tool, 2, 1, 1, 1)
        self.pushButton_Crimping_Select_Back = QtWidgets.QPushButton(self.page_Crimping_Select)
        self.pushButton_Crimping_Select_Back.setMinimumSize(QtCore.QSize(20, 680))
        self.pushButton_Crimping_Select_Back.setObjectName("pushButton_Crimping_Select_Back")
        self.gridLayout_6.addWidget(self.pushButton_Crimping_Select_Back, 1, 0, 3, 1)
        self.pushButton_Crimping_Maintenance = QtWidgets.QPushButton(self.page_Crimping_Select)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/Applicator-Crimper.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Crimping_Maintenance.setIcon(icon4)
        self.pushButton_Crimping_Maintenance.setIconSize(QtCore.QSize(200, 100))
        self.pushButton_Crimping_Maintenance.setObjectName("pushButton_Crimping_Maintenance")
        self.gridLayout_6.addWidget(self.pushButton_Crimping_Maintenance, 3, 1, 1, 1)
        self.pushButton_Crimping_Select_Crimping_Tool = QtWidgets.QPushButton(self.page_Crimping_Select)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/res/26733-2282213.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Crimping_Select_Crimping_Tool.setIcon(icon5)
        self.pushButton_Crimping_Select_Crimping_Tool.setIconSize(QtCore.QSize(200, 100))
        self.pushButton_Crimping_Select_Crimping_Tool.setObjectName("pushButton_Crimping_Select_Crimping_Tool")
        self.gridLayout_6.addWidget(self.pushButton_Crimping_Select_Crimping_Tool, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_Crimping_Select)
        self.pageMain = QtWidgets.QWidget()
        self.pageMain.setObjectName("pageMain")
        self.gridLayout = QtWidgets.QGridLayout(self.pageMain)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Main_Page_Back = QtWidgets.QPushButton(self.pageMain)
        self.pushButton_Main_Page_Back.setMinimumSize(QtCore.QSize(20, 680))
        self.pushButton_Main_Page_Back.setObjectName("pushButton_Main_Page_Back")
        self.gridLayout.addWidget(self.pushButton_Main_Page_Back, 1, 0, 3, 1)
        self.pushButtonParts = QtWidgets.QPushButton(self.pageMain)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonParts.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/res/imgonline-com-ua-Transparent-backgr-2Ise7PpJJUge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonParts.setIcon(icon6)
        self.pushButtonParts.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonParts.setObjectName("pushButtonParts")
        self.gridLayout.addWidget(self.pushButtonParts, 1, 1, 1, 1)
        self.pushButtonEngeneer = QtWidgets.QPushButton(self.pageMain)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEngeneer.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/res/Komax_Academy_216x160.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEngeneer.setIcon(icon7)
        self.pushButtonEngeneer.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonEngeneer.setObjectName("pushButtonEngeneer")
        self.gridLayout.addWidget(self.pushButtonEngeneer, 2, 2, 1, 1)
        self.pushButtonOperator = QtWidgets.QPushButton(self.pageMain)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOperator.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/res/992593_cms2image-fixedwidth-640x0_1ovuKH_TgrNff.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOperator.setIcon(icon8)
        self.pushButtonOperator.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonOperator.setObjectName("pushButtonOperator")
        self.gridLayout.addWidget(self.pushButtonOperator, 3, 2, 1, 1)
        self.pushButtonInput = QtWidgets.QPushButton(self.pageMain)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonInput.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/res/imgonline-com-ua-Transparent-backgr-n3eZB6XgI4Pg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonInput.setIcon(icon9)
        self.pushButtonInput.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonInput.setObjectName("pushButtonInput")
        self.gridLayout.addWidget(self.pushButtonInput, 2, 1, 1, 1)
        self.pushButtonStok = QtWidgets.QPushButton(self.pageMain)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStok.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/res/Schermata-2017-06-27-alle-17.36.44-495x400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStok.setIcon(icon10)
        self.pushButtonStok.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonStok.setObjectName("pushButtonStok")
        self.gridLayout.addWidget(self.pushButtonStok, 3, 1, 1, 1)
        self.pushButtonEquipment = QtWidgets.QPushButton(self.pageMain)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEquipment.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/res/Без названия.jfif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEquipment.setIcon(icon11)
        self.pushButtonEquipment.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonEquipment.setObjectName("pushButtonEquipment")
        self.gridLayout.addWidget(self.pushButtonEquipment, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.pageMain)
        self.page_Incoming = QtWidgets.QWidget()
        self.page_Incoming.setObjectName("page_Incoming")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_Incoming)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_Incoming_Back = QtWidgets.QPushButton(self.page_Incoming)
        self.pushButton_Incoming_Back.setMinimumSize(QtCore.QSize(50, 680))
        self.pushButton_Incoming_Back.setObjectName("pushButton_Incoming_Back")
        self.gridLayout_8.addWidget(self.pushButton_Incoming_Back, 0, 0, 7, 1)
        self.label_SPN = QtWidgets.QLabel(self.page_Incoming)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_SPN.setFont(font)
        self.label_SPN.setScaledContents(True)
        self.label_SPN.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SPN.setObjectName("label_SPN")
        self.gridLayout_8.addWidget(self.label_SPN, 0, 1, 1, 1)
        self.label_DPN = QtWidgets.QLabel(self.page_Incoming)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_DPN.setFont(font)
        self.label_DPN.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DPN.setObjectName("label_DPN")
        self.gridLayout_8.addWidget(self.label_DPN, 0, 2, 1, 1)
        self.label_Invoice_Number = QtWidgets.QLabel(self.page_Incoming)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Invoice_Number.setFont(font)
        self.label_Invoice_Number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Invoice_Number.setObjectName("label_Invoice_Number")
        self.gridLayout_8.addWidget(self.label_Invoice_Number, 0, 3, 1, 1)
        self.lineEdit_Incoming_SPN = QtWidgets.QLineEdit(self.page_Incoming)
        self.lineEdit_Incoming_SPN.setCursorPosition(0)
        self.lineEdit_Incoming_SPN.setObjectName("lineEdit_Incoming_SPN")
        self.gridLayout_8.addWidget(self.lineEdit_Incoming_SPN, 1, 1, 1, 1)
        self.lineEdit_DPN = QtWidgets.QLineEdit(self.page_Incoming)
        self.lineEdit_DPN.setCursorPosition(0)
        self.lineEdit_DPN.setObjectName("lineEdit_DPN")
        self.gridLayout_8.addWidget(self.lineEdit_DPN, 1, 2, 1, 1)
        self.lineEdit_Invoice_Number = QtWidgets.QLineEdit(self.page_Incoming)
        self.lineEdit_Invoice_Number.setObjectName("lineEdit_Invoice_Number")
        self.gridLayout_8.addWidget(self.lineEdit_Invoice_Number, 1, 3, 1, 1)
        self.label_QTY = QtWidgets.QLabel(self.page_Incoming)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_QTY.setFont(font)
        self.label_QTY.setAlignment(QtCore.Qt.AlignCenter)
        self.label_QTY.setObjectName("label_QTY")
        self.gridLayout_8.addWidget(self.label_QTY, 2, 1, 1, 1)
        self.label_Description = QtWidgets.QLabel(self.page_Incoming)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Description.setFont(font)
        self.label_Description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Description.setObjectName("label_Description")
        self.gridLayout_8.addWidget(self.label_Description, 2, 2, 1, 1)
        self.label_Store_place = QtWidgets.QLabel(self.page_Incoming)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Store_place.setFont(font)
        self.label_Store_place.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Store_place.setObjectName("label_Store_place")
        self.gridLayout_8.addWidget(self.label_Store_place, 2, 3, 1, 1)
        self.lineEdit_QTY = QtWidgets.QLineEdit(self.page_Incoming)
        self.lineEdit_QTY.setObjectName("lineEdit_QTY")
        self.gridLayout_8.addWidget(self.lineEdit_QTY, 3, 1, 1, 1)
        self.lineEdit_Description = QtWidgets.QLineEdit(self.page_Incoming)
        self.lineEdit_Description.setObjectName("lineEdit_Description")
        self.gridLayout_8.addWidget(self.lineEdit_Description, 3, 2, 1, 1)
        self.lineEdit_Store_place = QtWidgets.QLineEdit(self.page_Incoming)
        self.lineEdit_Store_place.setObjectName("lineEdit_Store_place")
        self.gridLayout_8.addWidget(self.lineEdit_Store_place, 3, 3, 1, 1)
        self.label_Price = QtWidgets.QLabel(self.page_Incoming)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Price.setFont(font)
        self.label_Price.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Price.setObjectName("label_Price")
        self.gridLayout_8.addWidget(self.label_Price, 4, 1, 1, 1)
        self.label_Date_Order = QtWidgets.QLabel(self.page_Incoming)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Date_Order.setFont(font)
        self.label_Date_Order.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Date_Order.setObjectName("label_Date_Order")
        self.gridLayout_8.addWidget(self.label_Date_Order, 4, 2, 1, 1)
        self.label_Date_Incoming = QtWidgets.QLabel(self.page_Incoming)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Date_Incoming.setFont(font)
        self.label_Date_Incoming.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Date_Incoming.setObjectName("label_Date_Incoming")
        self.gridLayout_8.addWidget(self.label_Date_Incoming, 4, 3, 1, 1)
        self.lineEdit_Price = QtWidgets.QLineEdit(self.page_Incoming)
        self.lineEdit_Price.setObjectName("lineEdit_Price")
        self.gridLayout_8.addWidget(self.lineEdit_Price, 5, 1, 1, 1)
        self.dateTimeEdit_Date_Order = QtWidgets.QDateTimeEdit(self.page_Incoming)
        self.dateTimeEdit_Date_Order.setCalendarPopup(True)
        self.dateTimeEdit_Date_Order.setObjectName("dateTimeEdit_Date_Order")
        self.gridLayout_8.addWidget(self.dateTimeEdit_Date_Order, 5, 2, 1, 1)
        self.dateEdit_Date_Incoming = QtWidgets.QDateEdit(self.page_Incoming)
        self.dateEdit_Date_Incoming.setCalendarPopup(True)
        self.dateEdit_Date_Incoming.setObjectName("dateEdit_Date_Incoming")
        self.gridLayout_8.addWidget(self.dateEdit_Date_Incoming, 5, 3, 1, 1)
        self.groupBox_Incoming = QtWidgets.QGroupBox(self.page_Incoming)
        self.groupBox_Incoming.setObjectName("groupBox_Incoming")
        self.radioButton_Incoming_SP = QtWidgets.QRadioButton(self.groupBox_Incoming)
        self.radioButton_Incoming_SP.setGeometry(QtCore.QRect(20, 30, 161, 21))
        self.radioButton_Incoming_SP.setObjectName("radioButton_Incoming_SP")
        self.radioButton_Incoming_WP = QtWidgets.QRadioButton(self.groupBox_Incoming)
        self.radioButton_Incoming_WP.setGeometry(QtCore.QRect(20, 60, 171, 31))
        self.radioButton_Incoming_WP.setObjectName("radioButton_Incoming_WP")
        self.gridLayout_8.addWidget(self.groupBox_Incoming, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page_Incoming)
        self.label.setMaximumSize(QtCore.QSize(200, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/res/imgonline-com-ua-Transparent-backgr-n3eZB6XgI4Pg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 6, 2, 1, 1)
        self.buttonBox_Incoming = QtWidgets.QDialogButtonBox(self.page_Incoming)
        self.buttonBox_Incoming.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Incoming.setObjectName("buttonBox_Incoming")
        self.gridLayout_8.addWidget(self.buttonBox_Incoming, 6, 3, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_Incoming)
        self.page_Parts = QtWidgets.QWidget()
        self.page_Parts.setObjectName("page_Parts")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_Parts)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_Parts_Back = QtWidgets.QPushButton(self.page_Parts)
        self.pushButton_Parts_Back.setMinimumSize(QtCore.QSize(50, 680))
        self.pushButton_Parts_Back.setObjectName("pushButton_Parts_Back")
        self.gridLayout_9.addWidget(self.pushButton_Parts_Back, 0, 0, 4, 1)
        self.label_SAP_NUMBER = QtWidgets.QLabel(self.page_Parts)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_SAP_NUMBER.setFont(font)
        self.label_SAP_NUMBER.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SAP_NUMBER.setObjectName("label_SAP_NUMBER")
        self.gridLayout_9.addWidget(self.label_SAP_NUMBER, 0, 3, 1, 1)
        self.buttonBox_Parts = QtWidgets.QDialogButtonBox(self.page_Parts)
        self.buttonBox_Parts.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Parts.setCenterButtons(True)
        self.buttonBox_Parts.setObjectName("buttonBox_Parts")
        self.gridLayout_9.addWidget(self.buttonBox_Parts, 2, 4, 1, 1)
        self.tableWidget_Parts = QtWidgets.QTableWidget(self.page_Parts)
        self.tableWidget_Parts.setObjectName("tableWidget_Parts")
        self.tableWidget_Parts.setColumnCount(0)
        self.tableWidget_Parts.setRowCount(0)
        self.gridLayout_9.addWidget(self.tableWidget_Parts, 3, 1, 1, 4)
        self.lineEdit_Parts_DPN = QtWidgets.QLineEdit(self.page_Parts)
        self.lineEdit_Parts_DPN.setObjectName("lineEdit_Parts_DPN")
        self.gridLayout_9.addWidget(self.lineEdit_Parts_DPN, 1, 1, 1, 1)
        self.lineEdit_SAP_NUMBER = QtWidgets.QLineEdit(self.page_Parts)
        self.lineEdit_SAP_NUMBER.setObjectName("lineEdit_SAP_NUMBER")
        self.gridLayout_9.addWidget(self.lineEdit_SAP_NUMBER, 1, 3, 1, 1)
        self.comboBox_Parts_Project = QtWidgets.QComboBox(self.page_Parts)
        self.comboBox_Parts_Project.setObjectName("comboBox_Parts_Project")
        self.gridLayout_9.addWidget(self.comboBox_Parts_Project, 1, 4, 1, 1)
        self.label_Parts_Projects = QtWidgets.QLabel(self.page_Parts)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Parts_Projects.setFont(font)
        self.label_Parts_Projects.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Parts_Projects.setObjectName("label_Parts_Projects")
        self.gridLayout_9.addWidget(self.label_Parts_Projects, 0, 4, 1, 1)
        self.groupBox_Parts_MaxMin = QtWidgets.QGroupBox(self.page_Parts)
        self.groupBox_Parts_MaxMin.setObjectName("groupBox_Parts_MaxMin")
        self.label_Parts_Max = QtWidgets.QLabel(self.groupBox_Parts_MaxMin)
        self.label_Parts_Max.setGeometry(QtCore.QRect(20, 30, 221, 31))
        self.label_Parts_Max.setObjectName("label_Parts_Max")
        self.label_Parts_Min = QtWidgets.QLabel(self.groupBox_Parts_MaxMin)
        self.label_Parts_Min.setGeometry(QtCore.QRect(20, 60, 221, 31))
        self.label_Parts_Min.setObjectName("label_Parts_Min")
        self.gridLayout_9.addWidget(self.groupBox_Parts_MaxMin, 2, 3, 1, 1)
        self.groupBox_Parts_Search_Type = QtWidgets.QGroupBox(self.page_Parts)
        self.groupBox_Parts_Search_Type.setObjectName("groupBox_Parts_Search_Type")
        self.radioButton_Parts_DPN = QtWidgets.QRadioButton(self.groupBox_Parts_Search_Type)
        self.radioButton_Parts_DPN.setGeometry(QtCore.QRect(40, 30, 82, 17))
        self.radioButton_Parts_DPN.setObjectName("radioButton_Parts_DPN")
        self.radioButton_Parts_Description = QtWidgets.QRadioButton(self.groupBox_Parts_Search_Type)
        self.radioButton_Parts_Description.setGeometry(QtCore.QRect(40, 50, 151, 31))
        self.radioButton_Parts_Description.setObjectName("radioButton_Parts_Description")
        self.gridLayout_9.addWidget(self.groupBox_Parts_Search_Type, 0, 1, 1, 1)
        self.groupBox_Parts_Building = QtWidgets.QGroupBox(self.page_Parts)
        self.groupBox_Parts_Building.setMinimumSize(QtCore.QSize(150, 100))
        self.groupBox_Parts_Building.setMaximumSize(QtCore.QSize(400, 200))
        self.groupBox_Parts_Building.setObjectName("groupBox_Parts_Building")
        self.radioButton_Parts_MQB1 = QtWidgets.QRadioButton(self.groupBox_Parts_Building)
        self.radioButton_Parts_MQB1.setGeometry(QtCore.QRect(10, 30, 211, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Parts_MQB1.setFont(font)
        self.radioButton_Parts_MQB1.setObjectName("radioButton_Parts_MQB1")
        self.radioButton_Parts_MQB2 = QtWidgets.QRadioButton(self.groupBox_Parts_Building)
        self.radioButton_Parts_MQB2.setGeometry(QtCore.QRect(10, 60, 191, 29))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Parts_MQB2.setFont(font)
        self.radioButton_Parts_MQB2.setObjectName("radioButton_Parts_MQB2")
        self.gridLayout_9.addWidget(self.groupBox_Parts_Building, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 0, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_Parts)
        self.page_EQIUPMENT = QtWidgets.QWidget()
        self.page_EQIUPMENT.setObjectName("page_EQIUPMENT")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_EQIUPMENT)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.radioButton_EQIUPMENT_MQB1 = QtWidgets.QRadioButton(self.page_EQIUPMENT)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_EQIUPMENT_MQB1.setFont(font)
        self.radioButton_EQIUPMENT_MQB1.setObjectName("radioButton_EQIUPMENT_MQB1")
        self.gridLayout_10.addWidget(self.radioButton_EQIUPMENT_MQB1, 3, 1, 1, 1)
        self.lineEdit_Serial_number = QtWidgets.QLineEdit(self.page_EQIUPMENT)
        self.lineEdit_Serial_number.setObjectName("lineEdit_Serial_number")
        self.gridLayout_10.addWidget(self.lineEdit_Serial_number, 1, 2, 1, 1)
        self.buttonBox_EQIUPMENT = QtWidgets.QDialogButtonBox(self.page_EQIUPMENT)
        self.buttonBox_EQIUPMENT.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_EQIUPMENT.setObjectName("buttonBox_EQIUPMENT")
        self.gridLayout_10.addWidget(self.buttonBox_EQIUPMENT, 5, 3, 1, 1)
        self.label_Serial_number = QtWidgets.QLabel(self.page_EQIUPMENT)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Serial_number.setFont(font)
        self.label_Serial_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Serial_number.setObjectName("label_Serial_number")
        self.gridLayout_10.addWidget(self.label_Serial_number, 0, 2, 1, 1)
        self.radioButton_EQIUPMENT_MQB2 = QtWidgets.QRadioButton(self.page_EQIUPMENT)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_EQIUPMENT_MQB2.setFont(font)
        self.radioButton_EQIUPMENT_MQB2.setObjectName("radioButton_EQIUPMENT_MQB2")
        self.gridLayout_10.addWidget(self.radioButton_EQIUPMENT_MQB2, 3, 3, 1, 1)
        self.pushButton_EQUIPMENT_Back = QtWidgets.QPushButton(self.page_EQIUPMENT)
        self.pushButton_EQUIPMENT_Back.setMinimumSize(QtCore.QSize(50, 680))
        self.pushButton_EQUIPMENT_Back.setObjectName("pushButton_EQUIPMENT_Back")
        self.gridLayout_10.addWidget(self.pushButton_EQUIPMENT_Back, 0, 0, 6, 1)
        self.label_EQP_Description = QtWidgets.QLabel(self.page_EQIUPMENT)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_EQP_Description.setFont(font)
        self.label_EQP_Description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_EQP_Description.setObjectName("label_EQP_Description")
        self.gridLayout_10.addWidget(self.label_EQP_Description, 0, 1, 1, 1)
        self.label_QS_Number = QtWidgets.QLabel(self.page_EQIUPMENT)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_QS_Number.setFont(font)
        self.label_QS_Number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_QS_Number.setObjectName("label_QS_Number")
        self.gridLayout_10.addWidget(self.label_QS_Number, 0, 3, 1, 1)
        self.lineEdit_EQP_Description = QtWidgets.QLineEdit(self.page_EQIUPMENT)
        self.lineEdit_EQP_Description.setObjectName("lineEdit_EQP_Description")
        self.gridLayout_10.addWidget(self.lineEdit_EQP_Description, 1, 1, 1, 1)
        self.lineEdit_QS_Number = QtWidgets.QLineEdit(self.page_EQIUPMENT)
        self.lineEdit_QS_Number.setObjectName("lineEdit_QS_Number")
        self.gridLayout_10.addWidget(self.lineEdit_QS_Number, 1, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem6, 2, 2, 1, 1)
        self.label_EQIUPMENT_picture = QtWidgets.QLabel(self.page_EQIUPMENT)
        self.label_EQIUPMENT_picture.setMaximumSize(QtCore.QSize(200, 150))
        self.label_EQIUPMENT_picture.setText("")
        self.label_EQIUPMENT_picture.setPixmap(QtGui.QPixmap(":/res/Без названия.jfif"))
        self.label_EQIUPMENT_picture.setScaledContents(True)
        self.label_EQIUPMENT_picture.setObjectName("label_EQIUPMENT_picture")
        self.gridLayout_10.addWidget(self.label_EQIUPMENT_picture, 3, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem7, 4, 2, 1, 1)
        self.label_EQIUPMENT_Date = QtWidgets.QLabel(self.page_EQIUPMENT)
        self.label_EQIUPMENT_Date.setObjectName("label_EQIUPMENT_Date")
        self.gridLayout_10.addWidget(self.label_EQIUPMENT_Date, 5, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_EQIUPMENT)
        self.page_maintenance = QtWidgets.QWidget()
        self.page_maintenance.setObjectName("page_maintenance")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_maintenance)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_maintenance_Tab_Number = QtWidgets.QLineEdit(self.page_maintenance)
        self.lineEdit_maintenance_Tab_Number.setObjectName("lineEdit_maintenance_Tab_Number")
        self.gridLayout_11.addWidget(self.lineEdit_maintenance_Tab_Number, 3, 1, 1, 1)
        self.ButtomBox_maintenance = QtWidgets.QDialogButtonBox(self.page_maintenance)
        self.ButtomBox_maintenance.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ButtomBox_maintenance.setObjectName("ButtomBox_maintenance")
        self.gridLayout_11.addWidget(self.ButtomBox_maintenance, 7, 2, 1, 1)
        self.tableWidget_Maintenance = QtWidgets.QTableWidget(self.page_maintenance)
        self.tableWidget_Maintenance.setObjectName("tableWidget_Maintenance")
        self.tableWidget_Maintenance.setColumnCount(0)
        self.tableWidget_Maintenance.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidget_Maintenance, 0, 2, 7, 1)
        self.label_maintenance_Area = QtWidgets.QLabel(self.page_maintenance)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_maintenance_Area.setFont(font)
        self.label_maintenance_Area.setObjectName("label_maintenance_Area")
        self.gridLayout_11.addWidget(self.label_maintenance_Area, 4, 1, 1, 1)
        self.label_Maintenance_picture = QtWidgets.QLabel(self.page_maintenance)
        self.label_Maintenance_picture.setMaximumSize(QtCore.QSize(400, 400))
        self.label_Maintenance_picture.setText("")
        self.label_Maintenance_picture.setPixmap(QtGui.QPixmap(":/res/Komax_Academy_216x160.jpg"))
        self.label_Maintenance_picture.setObjectName("label_Maintenance_picture")
        self.gridLayout_11.addWidget(self.label_Maintenance_picture, 6, 1, 2, 1)
        self.label_maintenance_Name = QtWidgets.QLabel(self.page_maintenance)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_maintenance_Name.setFont(font)
        self.label_maintenance_Name.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.label_maintenance_Name.setObjectName("label_maintenance_Name")
        self.gridLayout_11.addWidget(self.label_maintenance_Name, 0, 1, 1, 1)
        self.lineEdit_maintenance_Name = QtWidgets.QLineEdit(self.page_maintenance)
        self.lineEdit_maintenance_Name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_maintenance_Name.setText("")
        self.lineEdit_maintenance_Name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_maintenance_Name.setObjectName("lineEdit_maintenance_Name")
        self.gridLayout_11.addWidget(self.lineEdit_maintenance_Name, 1, 1, 1, 1)
        self.comboBox_maintenance_Area = QtWidgets.QComboBox(self.page_maintenance)
        self.comboBox_maintenance_Area.setObjectName("comboBox_maintenance_Area")
        self.gridLayout_11.addWidget(self.comboBox_maintenance_Area, 5, 1, 1, 1)
        self.pushButton_Maintenance_Back = QtWidgets.QPushButton(self.page_maintenance)
        self.pushButton_Maintenance_Back.setMinimumSize(QtCore.QSize(50, 680))
        self.pushButton_Maintenance_Back.setObjectName("pushButton_Maintenance_Back")
        self.gridLayout_11.addWidget(self.pushButton_Maintenance_Back, 0, 0, 8, 1)
        self.label_maintenance_Tab_Numer = QtWidgets.QLabel(self.page_maintenance)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_maintenance_Tab_Numer.setFont(font)
        self.label_maintenance_Tab_Numer.setObjectName("label_maintenance_Tab_Numer")
        self.gridLayout_11.addWidget(self.label_maintenance_Tab_Numer, 2, 1, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_maintenance)
        self.page_operators = QtWidgets.QWidget()
        self.page_operators.setObjectName("page_operators")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_operators)
        self.gridLayout_12.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_Operators_Back = QtWidgets.QPushButton(self.page_operators)
        self.pushButton_Operators_Back.setMinimumSize(QtCore.QSize(50, 680))
        self.pushButton_Operators_Back.setObjectName("pushButton_Operators_Back")
        self.gridLayout_12.addWidget(self.pushButton_Operators_Back, 0, 0, 8, 1)
        self.label_operators_Name = QtWidgets.QLabel(self.page_operators)
        self.label_operators_Name.setObjectName("label_operators_Name")
        self.gridLayout_12.addWidget(self.label_operators_Name, 0, 1, 1, 1)
        self.tableWidget_Operators = QtWidgets.QTableWidget(self.page_operators)
        self.tableWidget_Operators.setObjectName("tableWidget_Operators")
        self.tableWidget_Operators.setColumnCount(0)
        self.tableWidget_Operators.setRowCount(0)
        self.gridLayout_12.addWidget(self.tableWidget_Operators, 0, 2, 7, 1)
        self.lineEdit_operators_Name = QtWidgets.QLineEdit(self.page_operators)
        self.lineEdit_operators_Name.setObjectName("lineEdit_operators_Name")
        self.gridLayout_12.addWidget(self.lineEdit_operators_Name, 1, 1, 1, 1)
        self.label_operators_Tab_Number = QtWidgets.QLabel(self.page_operators)
        self.label_operators_Tab_Number.setObjectName("label_operators_Tab_Number")
        self.gridLayout_12.addWidget(self.label_operators_Tab_Number, 2, 1, 1, 1)
        self.lineEdit_operators_Tab_Number = QtWidgets.QLineEdit(self.page_operators)
        self.lineEdit_operators_Tab_Number.setObjectName("lineEdit_operators_Tab_Number")
        self.gridLayout_12.addWidget(self.lineEdit_operators_Tab_Number, 3, 1, 1, 1)
        self.label_operators_Team = QtWidgets.QLabel(self.page_operators)
        self.label_operators_Team.setObjectName("label_operators_Team")
        self.gridLayout_12.addWidget(self.label_operators_Team, 4, 1, 1, 1)
        self.comboBox_Operators_Team = QtWidgets.QComboBox(self.page_operators)
        self.comboBox_Operators_Team.setObjectName("comboBox_Operators_Team")
        self.gridLayout_12.addWidget(self.comboBox_Operators_Team, 5, 1, 1, 1)
        self.label_Operator_Picture = QtWidgets.QLabel(self.page_operators)
        self.label_Operator_Picture.setMaximumSize(QtCore.QSize(400, 400))
        self.label_Operator_Picture.setText("")
        self.label_Operator_Picture.setPixmap(QtGui.QPixmap(":/res/992593_cms2image-fixedwidth-640x0_1ovuKH_TgrNff.jpg"))
        self.label_Operator_Picture.setScaledContents(True)
        self.label_Operator_Picture.setObjectName("label_Operator_Picture")
        self.gridLayout_12.addWidget(self.label_Operator_Picture, 6, 1, 2, 1)
        self.buttonBox_Operators = QtWidgets.QDialogButtonBox(self.page_operators)
        self.buttonBox_Operators.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Operators.setObjectName("buttonBox_Operators")
        self.gridLayout_12.addWidget(self.buttonBox_Operators, 7, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_operators)
        self.page_Outgoing = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_Outgoing.sizePolicy().hasHeightForWidth())
        self.page_Outgoing.setSizePolicy(sizePolicy)
        self.page_Outgoing.setObjectName("page_Outgoing")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_Outgoing)
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_Outgoing_Back = QtWidgets.QPushButton(self.page_Outgoing)
        self.pushButton_Outgoing_Back.setMinimumSize(QtCore.QSize(50, 680))
        self.pushButton_Outgoing_Back.setObjectName("pushButton_Outgoing_Back")
        self.gridLayout_13.addWidget(self.pushButton_Outgoing_Back, 1, 0, 12, 1)
        self.label_Outgoing_DPN = QtWidgets.QLabel(self.page_Outgoing)
        self.label_Outgoing_DPN.setObjectName("label_Outgoing_DPN")
        self.gridLayout_13.addWidget(self.label_Outgoing_DPN, 1, 1, 1, 1)
        self.tableView_Outgoing = QtWidgets.QTableWidget(self.page_Outgoing)
        self.tableView_Outgoing.setObjectName("tableView_Outgoing")
        self.tableView_Outgoing.setColumnCount(0)
        self.tableView_Outgoing.setRowCount(0)
        self.gridLayout_13.addWidget(self.tableView_Outgoing, 1, 2, 8, 2)
        self.label_Outgoing_Equipment = QtWidgets.QLabel(self.page_Outgoing)
        self.label_Outgoing_Equipment.setObjectName("label_Outgoing_Equipment")
        self.gridLayout_13.addWidget(self.label_Outgoing_Equipment, 3, 1, 1, 1)
        self.lineEdit_Outgoing_DPN = QtWidgets.QLineEdit(self.page_Outgoing)
        self.lineEdit_Outgoing_DPN.setObjectName("lineEdit_Outgoing_DPN")
        self.gridLayout_13.addWidget(self.lineEdit_Outgoing_DPN, 2, 1, 1, 1)
        self.label_Outgoing_maintenance = QtWidgets.QLabel(self.page_Outgoing)
        self.label_Outgoing_maintenance.setObjectName("label_Outgoing_maintenance")
        self.gridLayout_13.addWidget(self.label_Outgoing_maintenance, 5, 1, 1, 1)
        self.comboBox_Outgoing_Equipment = QtWidgets.QComboBox(self.page_Outgoing)
        self.comboBox_Outgoing_Equipment.setObjectName("comboBox_Outgoing_Equipment")
        self.gridLayout_13.addWidget(self.comboBox_Outgoing_Equipment, 4, 1, 1, 1)
        self.comboBox_Outgoing_Reason = QtWidgets.QComboBox(self.page_Outgoing)
        self.comboBox_Outgoing_Reason.setObjectName("comboBox_Outgoing_Reason")
        self.gridLayout_13.addWidget(self.comboBox_Outgoing_Reason, 7, 1, 1, 1)
        self.label_Outgoing_QTY = QtWidgets.QLabel(self.page_Outgoing)
        self.label_Outgoing_QTY.setObjectName("label_Outgoing_QTY")
        self.gridLayout_13.addWidget(self.label_Outgoing_QTY, 8, 1, 1, 1)
        self.lineEdit_Outgoing_QTY = QtWidgets.QLineEdit(self.page_Outgoing)
        self.lineEdit_Outgoing_QTY.setObjectName("lineEdit_Outgoing_QTY")
        self.gridLayout_13.addWidget(self.lineEdit_Outgoing_QTY, 9, 1, 1, 1)
        self.label_Outgoing_Picture = QtWidgets.QLabel(self.page_Outgoing)
        self.label_Outgoing_Picture.setText("")
        self.label_Outgoing_Picture.setPixmap(QtGui.QPixmap(":/res/Schermata-2017-06-27-alle-17.36.44-495x400.png"))
        self.label_Outgoing_Picture.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Outgoing_Picture.setObjectName("label_Outgoing_Picture")
        self.gridLayout_13.addWidget(self.label_Outgoing_Picture, 9, 2, 3, 1)
        self.radioButton_Outgoing_MQB2 = QtWidgets.QRadioButton(self.page_Outgoing)
        self.radioButton_Outgoing_MQB2.setObjectName("radioButton_Outgoing_MQB2")
        self.gridLayout_13.addWidget(self.radioButton_Outgoing_MQB2, 10, 3, 1, 1)
        self.radioButton_Outgoing_MQB1 = QtWidgets.QRadioButton(self.page_Outgoing)
        self.radioButton_Outgoing_MQB1.setObjectName("radioButton_Outgoing_MQB1")
        self.gridLayout_13.addWidget(self.radioButton_Outgoing_MQB1, 9, 3, 1, 1)
        self.lineEdit_Outgoing_Scan_Key = QtWidgets.QLineEdit(self.page_Outgoing)
        self.lineEdit_Outgoing_Scan_Key.setObjectName("lineEdit_Outgoing_Scan_Key")
        self.gridLayout_13.addWidget(self.lineEdit_Outgoing_Scan_Key, 11, 1, 1, 1)
        self.buttonBox_Outgoing = QtWidgets.QDialogButtonBox(self.page_Outgoing)
        self.buttonBox_Outgoing.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Outgoing.setObjectName("buttonBox_Outgoing")
        self.gridLayout_13.addWidget(self.buttonBox_Outgoing, 12, 2, 1, 2)
        self.label_Outgoing_Scan_Key = QtWidgets.QLabel(self.page_Outgoing)
        self.label_Outgoing_Scan_Key.setObjectName("label_Outgoing_Scan_Key")
        self.gridLayout_13.addWidget(self.label_Outgoing_Scan_Key, 10, 1, 1, 1)
        self.label_Outgoing_Reason = QtWidgets.QLabel(self.page_Outgoing)
        self.label_Outgoing_Reason.setObjectName("label_Outgoing_Reason")
        self.gridLayout_13.addWidget(self.label_Outgoing_Reason, 6, 1, 1, 1)
        self.label_Outgoing_Date = QtWidgets.QLabel(self.page_Outgoing)
        self.label_Outgoing_Date.setObjectName("label_Outgoing_Date")
        self.gridLayout_13.addWidget(self.label_Outgoing_Date, 11, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem8, 0, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_Outgoing)
        self.page_Crimping_Die = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_Crimping_Die.sizePolicy().hasHeightForWidth())
        self.page_Crimping_Die.setSizePolicy(sizePolicy)
        self.page_Crimping_Die.setObjectName("page_Crimping_Die")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_Crimping_Die)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_Crimping_Die_Back = QtWidgets.QPushButton(self.page_Crimping_Die)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Crimping_Die_Back.sizePolicy().hasHeightForWidth())
        self.pushButton_Crimping_Die_Back.setSizePolicy(sizePolicy)
        self.pushButton_Crimping_Die_Back.setMinimumSize(QtCore.QSize(40, 680))
        self.pushButton_Crimping_Die_Back.setObjectName("pushButton_Crimping_Die_Back")
        self.gridLayout_14.addWidget(self.pushButton_Crimping_Die_Back, 0, 0, 6, 1)
        self.groupBox_Crimping_Die = QtWidgets.QGroupBox(self.page_Crimping_Die)
        self.groupBox_Crimping_Die.setObjectName("groupBox_Crimping_Die")
        self.radioButton_Crimping_Die__Incomming = QtWidgets.QRadioButton(self.groupBox_Crimping_Die)
        self.radioButton_Crimping_Die__Incomming.setGeometry(QtCore.QRect(20, 30, 141, 31))
        self.radioButton_Crimping_Die__Incomming.setObjectName("radioButton_Crimping_Die__Incomming")
        self.radioButton_Crimping_Die_Outgoing = QtWidgets.QRadioButton(self.groupBox_Crimping_Die)
        self.radioButton_Crimping_Die_Outgoing.setGeometry(QtCore.QRect(20, 60, 121, 41))
        self.radioButton_Crimping_Die_Outgoing.setObjectName("radioButton_Crimping_Die_Outgoing")
        self.gridLayout_14.addWidget(self.groupBox_Crimping_Die, 0, 1, 1, 1)
        self.label_Crimping_Die_Picture = QtWidgets.QLabel(self.page_Crimping_Die)
        self.label_Crimping_Die_Picture.setText("")
        self.label_Crimping_Die_Picture.setPixmap(QtGui.QPixmap(":/res/26733-2727347.jpg"))
        self.label_Crimping_Die_Picture.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Crimping_Die_Picture.setObjectName("label_Crimping_Die_Picture")
        self.gridLayout_14.addWidget(self.label_Crimping_Die_Picture, 0, 2, 1, 1)
        self.label_Crimping_Die_Date = QtWidgets.QLabel(self.page_Crimping_Die)
        self.label_Crimping_Die_Date.setObjectName("label_Crimping_Die_Date")
        self.gridLayout_14.addWidget(self.label_Crimping_Die_Date, 1, 1, 1, 1)
        self.label_Crimping_Die_Crimping_Tool = QtWidgets.QLabel(self.page_Crimping_Die)
        self.label_Crimping_Die_Crimping_Tool.setObjectName("label_Crimping_Die_Crimping_Tool")
        self.gridLayout_14.addWidget(self.label_Crimping_Die_Crimping_Tool, 1, 2, 1, 1)
        self.dateEdit_Crimping_Die_Date = QtWidgets.QDateEdit(self.page_Crimping_Die)
        self.dateEdit_Crimping_Die_Date.setCalendarPopup(True)
        self.dateEdit_Crimping_Die_Date.setObjectName("dateEdit_Crimping_Die_Date")
        self.gridLayout_14.addWidget(self.dateEdit_Crimping_Die_Date, 2, 1, 1, 1)
        self.lineEdit_Crimping_Die_Crimping_Tool = QtWidgets.QLineEdit(self.page_Crimping_Die)
        self.lineEdit_Crimping_Die_Crimping_Tool.setObjectName("lineEdit_Crimping_Die_Crimping_Tool")
        self.gridLayout_14.addWidget(self.lineEdit_Crimping_Die_Crimping_Tool, 2, 2, 1, 1)
        self.label_Crimping_Die_Equipment = QtWidgets.QLabel(self.page_Crimping_Die)
        self.label_Crimping_Die_Equipment.setObjectName("label_Crimping_Die_Equipment")
        self.gridLayout_14.addWidget(self.label_Crimping_Die_Equipment, 3, 1, 1, 1)
        self.label_Crimping_Die_Employee = QtWidgets.QLabel(self.page_Crimping_Die)
        self.label_Crimping_Die_Employee.setObjectName("label_Crimping_Die_Employee")
        self.gridLayout_14.addWidget(self.label_Crimping_Die_Employee, 3, 2, 1, 1)
        self.comboBox_Crimping_Die_Equipment = QtWidgets.QComboBox(self.page_Crimping_Die)
        self.comboBox_Crimping_Die_Equipment.setObjectName("comboBox_Crimping_Die_Equipment")
        self.gridLayout_14.addWidget(self.comboBox_Crimping_Die_Equipment, 4, 1, 1, 1)
        self.lineEdit_Crimping_Die_Employee = QtWidgets.QLineEdit(self.page_Crimping_Die)
        self.lineEdit_Crimping_Die_Employee.setObjectName("lineEdit_Crimping_Die_Employee")
        self.gridLayout_14.addWidget(self.lineEdit_Crimping_Die_Employee, 4, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(482, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem9, 5, 1, 1, 1)
        self.buttonBox_Crimping_Die = QtWidgets.QDialogButtonBox(self.page_Crimping_Die)
        self.buttonBox_Crimping_Die.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Crimping_Die.setObjectName("buttonBox_Crimping_Die")
        self.gridLayout_14.addWidget(self.buttonBox_Crimping_Die, 5, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_Crimping_Die)
        self.page_Crimping_Maintenance = QtWidgets.QWidget()
        self.page_Crimping_Maintenance.setObjectName("page_Crimping_Maintenance")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_Crimping_Maintenance)
        self.gridLayout_15.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_15.setSpacing(6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.pushButton_Crimping_Maintenance_Back = QtWidgets.QPushButton(self.page_Crimping_Maintenance)
        self.pushButton_Crimping_Maintenance_Back.setMinimumSize(QtCore.QSize(40, 680))
        self.pushButton_Crimping_Maintenance_Back.setObjectName("pushButton_Crimping_Maintenance_Back")
        self.gridLayout_15.addWidget(self.pushButton_Crimping_Maintenance_Back, 0, 0, 6, 1)
        self.groupBox_Crimping_Maintenance = QtWidgets.QGroupBox(self.page_Crimping_Maintenance)
        self.groupBox_Crimping_Maintenance.setObjectName("groupBox_Crimping_Maintenance")
        self.radioButton_Crimping_Maintenance_Incomming = QtWidgets.QRadioButton(self.groupBox_Crimping_Maintenance)
        self.radioButton_Crimping_Maintenance_Incomming.setGeometry(QtCore.QRect(20, 30, 241, 51))
        self.radioButton_Crimping_Maintenance_Incomming.setObjectName("radioButton_Crimping_Maintenance_Incomming")
        self.radioButton_Crimping_Maintenance_Outgoing = QtWidgets.QRadioButton(self.groupBox_Crimping_Maintenance)
        self.radioButton_Crimping_Maintenance_Outgoing.setGeometry(QtCore.QRect(20, 70, 251, 41))
        self.radioButton_Crimping_Maintenance_Outgoing.setObjectName("radioButton_Crimping_Maintenance_Outgoing")
        self.gridLayout_15.addWidget(self.groupBox_Crimping_Maintenance, 0, 1, 1, 1)
        self.label_Crimping_Maintenance_Picture = QtWidgets.QLabel(self.page_Crimping_Maintenance)
        self.label_Crimping_Maintenance_Picture.setText("")
        self.label_Crimping_Maintenance_Picture.setPixmap(QtGui.QPixmap(":/res/Applicator-Crimper.jpg"))
        self.label_Crimping_Maintenance_Picture.setScaledContents(True)
        self.label_Crimping_Maintenance_Picture.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Crimping_Maintenance_Picture.setObjectName("label_Crimping_Maintenance_Picture")
        self.gridLayout_15.addWidget(self.label_Crimping_Maintenance_Picture, 0, 2, 1, 1)
        self.label_Crimping_Maintenance_Date = QtWidgets.QLabel(self.page_Crimping_Maintenance)
        self.label_Crimping_Maintenance_Date.setObjectName("label_Crimping_Maintenance_Date")
        self.gridLayout_15.addWidget(self.label_Crimping_Maintenance_Date, 1, 1, 1, 1)
        self.label_Crimping_Maintenance_Crimping_Tool = QtWidgets.QLabel(self.page_Crimping_Maintenance)
        self.label_Crimping_Maintenance_Crimping_Tool.setObjectName("label_Crimping_Maintenance_Crimping_Tool")
        self.gridLayout_15.addWidget(self.label_Crimping_Maintenance_Crimping_Tool, 1, 2, 1, 1)
        self.dateEdit_Crimping_Maintenance = QtWidgets.QDateEdit(self.page_Crimping_Maintenance)
        self.dateEdit_Crimping_Maintenance.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEdit_Crimping_Maintenance.setCalendarPopup(True)
        self.dateEdit_Crimping_Maintenance.setObjectName("dateEdit_Crimping_Maintenance")
        self.gridLayout_15.addWidget(self.dateEdit_Crimping_Maintenance, 2, 1, 1, 1)
        self.lineEdit_Crimping_Maintenance_Crimping_Tool = QtWidgets.QLineEdit(self.page_Crimping_Maintenance)
        self.lineEdit_Crimping_Maintenance_Crimping_Tool.setObjectName("lineEdit_Crimping_Maintenance_Crimping_Tool")
        self.gridLayout_15.addWidget(self.lineEdit_Crimping_Maintenance_Crimping_Tool, 2, 2, 1, 1)
        self.label_Crimping_Maintenance_Employee = QtWidgets.QLabel(self.page_Crimping_Maintenance)
        self.label_Crimping_Maintenance_Employee.setObjectName("label_Crimping_Maintenance_Employee")
        self.gridLayout_15.addWidget(self.label_Crimping_Maintenance_Employee, 3, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(482, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem10, 4, 1, 1, 1)
        self.lineEdit_Crimping_Maintenance_Employee = QtWidgets.QLineEdit(self.page_Crimping_Maintenance)
        self.lineEdit_Crimping_Maintenance_Employee.setEnabled(True)
        self.lineEdit_Crimping_Maintenance_Employee.setObjectName("lineEdit_Crimping_Maintenance_Employee")
        self.gridLayout_15.addWidget(self.lineEdit_Crimping_Maintenance_Employee, 4, 2, 1, 1)
        self.buttonBox_Crimping_Maintenance = QtWidgets.QDialogButtonBox(self.page_Crimping_Maintenance)
        self.buttonBox_Crimping_Maintenance.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Crimping_Maintenance.setObjectName("buttonBox_Crimping_Maintenance")
        self.gridLayout_15.addWidget(self.buttonBox_Crimping_Maintenance, 5, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_Crimping_Maintenance)
        self.page_Crimping_Terminal = QtWidgets.QWidget()
        self.page_Crimping_Terminal.setObjectName("page_Crimping_Terminal")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_Crimping_Terminal)
        self.gridLayout_16.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.pushButton_Crimping_Terminal_Back = QtWidgets.QPushButton(self.page_Crimping_Terminal)
        self.pushButton_Crimping_Terminal_Back.setMinimumSize(QtCore.QSize(40, 680))
        self.pushButton_Crimping_Terminal_Back.setObjectName("pushButton_Crimping_Terminal_Back")
        self.gridLayout_16.addWidget(self.pushButton_Crimping_Terminal_Back, 0, 0, 6, 1)
        self.groupBox_Crimping_Terminal = QtWidgets.QGroupBox(self.page_Crimping_Terminal)
        self.groupBox_Crimping_Terminal.setObjectName("groupBox_Crimping_Terminal")
        self.radioButton_Crimping_Terminal_Incoming = QtWidgets.QRadioButton(self.groupBox_Crimping_Terminal)
        self.radioButton_Crimping_Terminal_Incoming.setGeometry(QtCore.QRect(20, 30, 141, 31))
        self.radioButton_Crimping_Terminal_Incoming.setObjectName("radioButton_Crimping_Terminal_Incoming")
        self.radioButton_Crimping_Terminal_Outgoing = QtWidgets.QRadioButton(self.groupBox_Crimping_Terminal)
        self.radioButton_Crimping_Terminal_Outgoing.setGeometry(QtCore.QRect(20, 60, 121, 41))
        self.radioButton_Crimping_Terminal_Outgoing.setObjectName("radioButton_Crimping_Terminal_Outgoing")
        self.gridLayout_16.addWidget(self.groupBox_Crimping_Terminal, 0, 1, 1, 1)
        self.label_Crimping_Terminal = QtWidgets.QLabel(self.page_Crimping_Terminal)
        self.label_Crimping_Terminal.setMaximumSize(QtCore.QSize(200, 200))
        self.label_Crimping_Terminal.setText("")
        self.label_Crimping_Terminal.setPixmap(QtGui.QPixmap(":/res/41nLbUHoArL.jpg"))
        self.label_Crimping_Terminal.setScaledContents(True)
        self.label_Crimping_Terminal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Crimping_Terminal.setObjectName("label_Crimping_Terminal")
        self.gridLayout_16.addWidget(self.label_Crimping_Terminal, 0, 2, 1, 1)
        self.label_Crimping_Terminal_2 = QtWidgets.QLabel(self.page_Crimping_Terminal)
        self.label_Crimping_Terminal_2.setObjectName("label_Crimping_Terminal_2")
        self.gridLayout_16.addWidget(self.label_Crimping_Terminal_2, 1, 1, 1, 1)
        self.label_Crimping_Terminal_Crimping_Tool = QtWidgets.QLabel(self.page_Crimping_Terminal)
        self.label_Crimping_Terminal_Crimping_Tool.setObjectName("label_Crimping_Terminal_Crimping_Tool")
        self.gridLayout_16.addWidget(self.label_Crimping_Terminal_Crimping_Tool, 1, 2, 1, 1)
        self.dateEdit_Crimping_Terminal = QtWidgets.QDateEdit(self.page_Crimping_Terminal)
        self.dateEdit_Crimping_Terminal.setCalendarPopup(True)
        self.dateEdit_Crimping_Terminal.setObjectName("dateEdit_Crimping_Terminal")
        self.gridLayout_16.addWidget(self.dateEdit_Crimping_Terminal, 2, 1, 1, 1)
        self.lineEdit_Crimping_Terminal_Crimping_Tool = QtWidgets.QLineEdit(self.page_Crimping_Terminal)
        self.lineEdit_Crimping_Terminal_Crimping_Tool.setObjectName("lineEdit_Crimping_Terminal_Crimping_Tool")
        self.gridLayout_16.addWidget(self.lineEdit_Crimping_Terminal_Crimping_Tool, 2, 2, 1, 1)
        self.label_Crimping_Terminal_Equipment = QtWidgets.QLabel(self.page_Crimping_Terminal)
        self.label_Crimping_Terminal_Equipment.setObjectName("label_Crimping_Terminal_Equipment")
        self.gridLayout_16.addWidget(self.label_Crimping_Terminal_Equipment, 3, 1, 1, 1)
        self.label_Crimping_Terminal_Employee = QtWidgets.QLabel(self.page_Crimping_Terminal)
        self.label_Crimping_Terminal_Employee.setObjectName("label_Crimping_Terminal_Employee")
        self.gridLayout_16.addWidget(self.label_Crimping_Terminal_Employee, 3, 2, 1, 1)
        self.comboBox_Crimping_Terminal_Equipment = QtWidgets.QComboBox(self.page_Crimping_Terminal)
        self.comboBox_Crimping_Terminal_Equipment.setObjectName("comboBox_Crimping_Terminal_Equipment")
        self.gridLayout_16.addWidget(self.comboBox_Crimping_Terminal_Equipment, 4, 1, 1, 1)
        self.lineEdit_Crimping_Terminal_Employee = QtWidgets.QLineEdit(self.page_Crimping_Terminal)
        self.lineEdit_Crimping_Terminal_Employee.setObjectName("lineEdit_Crimping_Terminal_Employee")
        self.gridLayout_16.addWidget(self.lineEdit_Crimping_Terminal_Employee, 4, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(482, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem11, 5, 1, 1, 1)
        self.buttonBox_Crimping_Terminal = QtWidgets.QDialogButtonBox(self.page_Crimping_Terminal)
        self.buttonBox_Crimping_Terminal.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Crimping_Terminal.setObjectName("buttonBox_Crimping_Terminal")
        self.gridLayout_16.addWidget(self.buttonBox_Crimping_Terminal, 5, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_Crimping_Terminal)
        self.pageReports = QtWidgets.QWidget()
        self.pageReports.setObjectName("pageReports")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageReports)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonPartsEmploeeReport = QtWidgets.QPushButton(self.pageReports)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPartsEmploeeReport.setFont(font)
        self.pushButtonPartsEmploeeReport.setObjectName("pushButtonPartsEmploeeReport")
        self.gridLayout_2.addWidget(self.pushButtonPartsEmploeeReport, 1, 2, 1, 1)
        self.pushButtonMounthlyStockProduction = QtWidgets.QPushButton(self.pageReports)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonMounthlyStockProduction.setFont(font)
        self.pushButtonMounthlyStockProduction.setObjectName("pushButtonMounthlyStockProduction")
        self.gridLayout_2.addWidget(self.pushButtonMounthlyStockProduction, 3, 2, 1, 1)
        self.pushButtonOrderReport = QtWidgets.QPushButton(self.pageReports)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOrderReport.setFont(font)
        self.pushButtonOrderReport.setObjectName("pushButtonOrderReport")
        self.gridLayout_2.addWidget(self.pushButtonOrderReport, 3, 1, 1, 1)
        self.pushButtonPartsMachineReport = QtWidgets.QPushButton(self.pageReports)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPartsMachineReport.setFont(font)
        self.pushButtonPartsMachineReport.setObjectName("pushButtonPartsMachineReport")
        self.gridLayout_2.addWidget(self.pushButtonPartsMachineReport, 4, 1, 1, 1)
        self.pushButtonTimeLifeSP = QtWidgets.QPushButton(self.pageReports)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTimeLifeSP.setFont(font)
        self.pushButtonTimeLifeSP.setObjectName("pushButtonTimeLifeSP")
        self.gridLayout_2.addWidget(self.pushButtonTimeLifeSP, 4, 2, 1, 1)
        self.pushButtonStockReport = QtWidgets.QPushButton(self.pageReports)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStockReport.setFont(font)
        self.pushButtonStockReport.setObjectName("pushButtonStockReport")
        self.gridLayout_2.addWidget(self.pushButtonStockReport, 1, 1, 1, 1)
        self.pushButton_Reports_Back = QtWidgets.QPushButton(self.pageReports)
        self.pushButton_Reports_Back.setMinimumSize(QtCore.QSize(40, 680))
        self.pushButton_Reports_Back.setObjectName("pushButton_Reports_Back")
        self.gridLayout_2.addWidget(self.pushButton_Reports_Back, 1, 0, 4, 1)
        self.pushButtonMounthlyStockCutting = QtWidgets.QPushButton(self.pageReports)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonMounthlyStockCutting.setFont(font)
        self.pushButtonMounthlyStockCutting.setObjectName("pushButtonMounthlyStockCutting")
        self.gridLayout_2.addWidget(self.pushButtonMounthlyStockCutting, 2, 2, 1, 1)
        self.pushButtonDailyReport = QtWidgets.QPushButton(self.pageReports)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDailyReport.setFont(font)
        self.pushButtonDailyReport.setObjectName("pushButtonDailyReport")
        self.gridLayout_2.addWidget(self.pushButtonDailyReport, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 0, 2, 1, 1)
        self.stackedWidget_SP.addWidget(self.pageReports)
        self.page_Stock_report = QtWidgets.QWidget()
        self.page_Stock_report.setObjectName("page_Stock_report")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.page_Stock_report)
        self.gridLayout_17.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_17.setSpacing(6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.buttonBox_Stock_report_ = QtWidgets.QDialogButtonBox(self.page_Stock_report)
        self.buttonBox_Stock_report_.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_Stock_report_.setObjectName("buttonBox_Stock_report_")
        self.gridLayout_17.addWidget(self.buttonBox_Stock_report_, 3, 1, 1, 1)
        self.pushButton_Stock_report_excel = QtWidgets.QPushButton(self.page_Stock_report)
        self.pushButton_Stock_report_excel.setObjectName("pushButton_Stock_report_excel")
        self.gridLayout_17.addWidget(self.pushButton_Stock_report_excel, 2, 1, 1, 1)
        self.pushButton_Stock_report_Back = QtWidgets.QPushButton(self.page_Stock_report)
        self.pushButton_Stock_report_Back.setMinimumSize(QtCore.QSize(40, 680))
        self.pushButton_Stock_report_Back.setObjectName("pushButton_Stock_report_Back")
        self.gridLayout_17.addWidget(self.pushButton_Stock_report_Back, 1, 0, 1, 1)
        self.pushButton_Stock_report_refresh = QtWidgets.QPushButton(self.page_Stock_report)
        self.pushButton_Stock_report_refresh.setObjectName("pushButton_Stock_report_refresh")
        self.gridLayout_17.addWidget(self.pushButton_Stock_report_refresh, 0, 1, 1, 1)
        self.tableWidget_Stock_report = QtWidgets.QTableWidget(self.page_Stock_report)
        self.tableWidget_Stock_report.setObjectName("tableWidget_Stock_report")
        self.tableWidget_Stock_report.setColumnCount(0)
        self.tableWidget_Stock_report.setRowCount(0)
        self.gridLayout_17.addWidget(self.tableWidget_Stock_report, 1, 1, 1, 1)
        self.stackedWidget_SP.addWidget(self.page_Stock_report)
        self.gridLayout_4.addWidget(self.stackedWidget_SP, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget_SP)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1109, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.labelLogining.setBuddy(self.lineEditLogin)
        self.labelPassword.setBuddy(self.lineEditPassword)
        self.label_EQIUPMENT_picture.setBuddy(self.radioButton_EQIUPMENT_MQB2)
        self.label_maintenance_Area.setBuddy(self.tableWidget_Maintenance)
        self.label_operators_Name.setBuddy(self.tableWidget_Operators)
        self.label_Outgoing_Picture.setBuddy(self.radioButton_Outgoing_MQB2)

        self.retranslateUi(MainWindow)
        self.stackedWidget_SP.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditLogin, self.lineEditPassword)
        MainWindow.setTabOrder(self.lineEditPassword, self.pushButton_Main_Spare_Parts)
        MainWindow.setTabOrder(self.pushButton_Main_Spare_Parts, self.pushButton_Main_Report)
        MainWindow.setTabOrder(self.pushButton_Main_Report, self.pushButton_Crimping_Die)
        MainWindow.setTabOrder(self.pushButton_Crimping_Die, self.pushButton_Crimping_Select_Crimping_Tool)
        MainWindow.setTabOrder(self.pushButton_Crimping_Select_Crimping_Tool, self.pushButton_Crimping_Select_Tool)
        MainWindow.setTabOrder(self.pushButton_Crimping_Select_Tool, self.pushButton_Crimping_Maintenance)
        MainWindow.setTabOrder(self.pushButton_Crimping_Maintenance, self.pushButton_Crimping_Select_Back)
        MainWindow.setTabOrder(self.pushButton_Crimping_Select_Back, self.pushButtonParts)
        MainWindow.setTabOrder(self.pushButtonParts, self.pushButtonEquipment)
        MainWindow.setTabOrder(self.pushButtonEquipment, self.pushButtonInput)
        MainWindow.setTabOrder(self.pushButtonInput, self.pushButtonEngeneer)
        MainWindow.setTabOrder(self.pushButtonEngeneer, self.pushButtonStok)
        MainWindow.setTabOrder(self.pushButtonStok, self.pushButtonOperator)
        MainWindow.setTabOrder(self.pushButtonOperator, self.pushButton_Main_Page_Back)
        MainWindow.setTabOrder(self.pushButton_Main_Page_Back, self.lineEdit_Incoming_SPN)
        MainWindow.setTabOrder(self.lineEdit_Incoming_SPN, self.lineEdit_DPN)
        MainWindow.setTabOrder(self.lineEdit_DPN, self.lineEdit_Invoice_Number)
        MainWindow.setTabOrder(self.lineEdit_Invoice_Number, self.lineEdit_QTY)
        MainWindow.setTabOrder(self.lineEdit_QTY, self.lineEdit_Description)
        MainWindow.setTabOrder(self.lineEdit_Description, self.lineEdit_Store_place)
        MainWindow.setTabOrder(self.lineEdit_Store_place, self.lineEdit_Price)
        MainWindow.setTabOrder(self.lineEdit_Price, self.dateTimeEdit_Date_Order)
        MainWindow.setTabOrder(self.dateTimeEdit_Date_Order, self.dateEdit_Date_Incoming)
        MainWindow.setTabOrder(self.dateEdit_Date_Incoming, self.radioButton_Incoming_SP)
        MainWindow.setTabOrder(self.radioButton_Incoming_SP, self.radioButton_Incoming_WP)
        MainWindow.setTabOrder(self.radioButton_Incoming_WP, self.pushButton_Incoming_Back)
        MainWindow.setTabOrder(self.pushButton_Incoming_Back, self.radioButton_Parts_DPN)
        MainWindow.setTabOrder(self.radioButton_Parts_DPN, self.radioButton_Parts_Description)
        MainWindow.setTabOrder(self.radioButton_Parts_Description, self.lineEdit_Parts_DPN)
        MainWindow.setTabOrder(self.lineEdit_Parts_DPN, self.lineEdit_SAP_NUMBER)
        MainWindow.setTabOrder(self.lineEdit_SAP_NUMBER, self.comboBox_Parts_Project)
        MainWindow.setTabOrder(self.comboBox_Parts_Project, self.radioButton_Parts_MQB1)
        MainWindow.setTabOrder(self.radioButton_Parts_MQB1, self.radioButton_Parts_MQB2)
        MainWindow.setTabOrder(self.radioButton_Parts_MQB2, self.tableWidget_Parts)
        MainWindow.setTabOrder(self.tableWidget_Parts, self.pushButton_Parts_Back)
        MainWindow.setTabOrder(self.pushButton_Parts_Back, self.lineEdit_EQP_Description)
        MainWindow.setTabOrder(self.lineEdit_EQP_Description, self.lineEdit_Serial_number)
        MainWindow.setTabOrder(self.lineEdit_Serial_number, self.lineEdit_QS_Number)
        MainWindow.setTabOrder(self.lineEdit_QS_Number, self.radioButton_EQIUPMENT_MQB1)
        MainWindow.setTabOrder(self.radioButton_EQIUPMENT_MQB1, self.radioButton_EQIUPMENT_MQB2)
        MainWindow.setTabOrder(self.radioButton_EQIUPMENT_MQB2, self.pushButton_EQUIPMENT_Back)
        MainWindow.setTabOrder(self.pushButton_EQUIPMENT_Back, self.lineEdit_maintenance_Name)
        MainWindow.setTabOrder(self.lineEdit_maintenance_Name, self.lineEdit_maintenance_Tab_Number)
        MainWindow.setTabOrder(self.lineEdit_maintenance_Tab_Number, self.comboBox_maintenance_Area)
        MainWindow.setTabOrder(self.comboBox_maintenance_Area, self.tableWidget_Maintenance)
        MainWindow.setTabOrder(self.tableWidget_Maintenance, self.pushButton_Maintenance_Back)
        MainWindow.setTabOrder(self.pushButton_Maintenance_Back, self.lineEdit_operators_Name)
        MainWindow.setTabOrder(self.lineEdit_operators_Name, self.lineEdit_operators_Tab_Number)
        MainWindow.setTabOrder(self.lineEdit_operators_Tab_Number, self.comboBox_Operators_Team)
        MainWindow.setTabOrder(self.comboBox_Operators_Team, self.tableWidget_Operators)
        MainWindow.setTabOrder(self.tableWidget_Operators, self.pushButton_Operators_Back)
        MainWindow.setTabOrder(self.pushButton_Operators_Back, self.lineEdit_Outgoing_Scan_Key)
        MainWindow.setTabOrder(self.lineEdit_Outgoing_Scan_Key, self.lineEdit_Outgoing_DPN)
        MainWindow.setTabOrder(self.lineEdit_Outgoing_DPN, self.comboBox_Outgoing_Equipment)
        MainWindow.setTabOrder(self.comboBox_Outgoing_Equipment, self.comboBox_Outgoing_Reason)
        MainWindow.setTabOrder(self.comboBox_Outgoing_Reason, self.lineEdit_Outgoing_QTY)
        MainWindow.setTabOrder(self.lineEdit_Outgoing_QTY, self.tableView_Outgoing)
        MainWindow.setTabOrder(self.tableView_Outgoing, self.pushButton_Outgoing_Back)
        MainWindow.setTabOrder(self.pushButton_Outgoing_Back, self.radioButton_Outgoing_MQB1)
        MainWindow.setTabOrder(self.radioButton_Outgoing_MQB1, self.radioButton_Outgoing_MQB2)
        MainWindow.setTabOrder(self.radioButton_Outgoing_MQB2, self.radioButton_Crimping_Die__Incomming)
        MainWindow.setTabOrder(self.radioButton_Crimping_Die__Incomming, self.radioButton_Crimping_Die_Outgoing)
        MainWindow.setTabOrder(self.radioButton_Crimping_Die_Outgoing, self.lineEdit_Crimping_Die_Employee)
        MainWindow.setTabOrder(self.lineEdit_Crimping_Die_Employee, self.lineEdit_Crimping_Die_Crimping_Tool)
        MainWindow.setTabOrder(self.lineEdit_Crimping_Die_Crimping_Tool, self.comboBox_Crimping_Die_Equipment)
        MainWindow.setTabOrder(self.comboBox_Crimping_Die_Equipment, self.dateEdit_Crimping_Die_Date)
        MainWindow.setTabOrder(self.dateEdit_Crimping_Die_Date, self.pushButton_Crimping_Die_Back)
        MainWindow.setTabOrder(self.pushButton_Crimping_Die_Back, self.radioButton_Crimping_Maintenance_Incomming)
        MainWindow.setTabOrder(self.radioButton_Crimping_Maintenance_Incomming, self.radioButton_Crimping_Maintenance_Outgoing)
        MainWindow.setTabOrder(self.radioButton_Crimping_Maintenance_Outgoing, self.lineEdit_Crimping_Maintenance_Employee)
        MainWindow.setTabOrder(self.lineEdit_Crimping_Maintenance_Employee, self.lineEdit_Crimping_Maintenance_Crimping_Tool)
        MainWindow.setTabOrder(self.lineEdit_Crimping_Maintenance_Crimping_Tool, self.dateEdit_Crimping_Maintenance)
        MainWindow.setTabOrder(self.dateEdit_Crimping_Maintenance, self.pushButton_Crimping_Maintenance_Back)
        MainWindow.setTabOrder(self.pushButton_Crimping_Maintenance_Back, self.radioButton_Crimping_Terminal_Incoming)
        MainWindow.setTabOrder(self.radioButton_Crimping_Terminal_Incoming, self.radioButton_Crimping_Terminal_Outgoing)
        MainWindow.setTabOrder(self.radioButton_Crimping_Terminal_Outgoing, self.lineEdit_Crimping_Terminal_Employee)
        MainWindow.setTabOrder(self.lineEdit_Crimping_Terminal_Employee, self.lineEdit_Crimping_Terminal_Crimping_Tool)
        MainWindow.setTabOrder(self.lineEdit_Crimping_Terminal_Crimping_Tool, self.dateEdit_Crimping_Terminal)
        MainWindow.setTabOrder(self.dateEdit_Crimping_Terminal, self.comboBox_Crimping_Terminal_Equipment)
        MainWindow.setTabOrder(self.comboBox_Crimping_Terminal_Equipment, self.pushButton_Crimping_Terminal_Back)
        MainWindow.setTabOrder(self.pushButton_Crimping_Terminal_Back, self.pushButtonStockReport)
        MainWindow.setTabOrder(self.pushButtonStockReport, self.pushButtonPartsEmploeeReport)
        MainWindow.setTabOrder(self.pushButtonPartsEmploeeReport, self.pushButtonDailyReport)
        MainWindow.setTabOrder(self.pushButtonDailyReport, self.pushButtonMounthlyStockCutting)
        MainWindow.setTabOrder(self.pushButtonMounthlyStockCutting, self.pushButtonOrderReport)
        MainWindow.setTabOrder(self.pushButtonOrderReport, self.pushButtonMounthlyStockProduction)
        MainWindow.setTabOrder(self.pushButtonMounthlyStockProduction, self.pushButtonPartsMachineReport)
        MainWindow.setTabOrder(self.pushButtonPartsMachineReport, self.pushButtonTimeLifeSP)
        MainWindow.setTabOrder(self.pushButtonTimeLifeSP, self.pushButton_Reports_Back)
        MainWindow.setTabOrder(self.pushButton_Reports_Back, self.pushButton_Stock_report_refresh)
        MainWindow.setTabOrder(self.pushButton_Stock_report_refresh, self.tableWidget_Stock_report)
        MainWindow.setTabOrder(self.tableWidget_Stock_report, self.pushButton_Stock_report_excel)
        MainWindow.setTabOrder(self.pushButton_Stock_report_excel, self.pushButton_Stock_report_Back)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_Logining.setTitle(_translate("MainWindow", "Spare Parts"))
        self.labelLogining.setText(_translate("MainWindow", "Login"))
        self.labelPassword.setText(_translate("MainWindow", "Password"))
        self.pushButton_Main_Spare_Parts.setText(_translate("MainWindow", "SPARE PARTS"))
        self.pushButton_Main_Report.setText(_translate("MainWindow", "         REPORTS"))
        self.pushButton_Crimping_Die.setText(_translate("MainWindow", "CRIMPING DIE"))
        self.pushButton_Crimping_Select_Tool.setText(_translate("MainWindow", "        Terminal                     "))
        self.pushButton_Crimping_Select_Back.setText(_translate("MainWindow", "<-"))
        self.pushButton_Crimping_Maintenance.setText(_translate("MainWindow", "Crimping Maintenance"))
        self.pushButton_Crimping_Select_Crimping_Tool.setText(_translate("MainWindow", "       Crimping Tools            "))
        self.pushButton_Main_Page_Back.setText(_translate("MainWindow", "<-"))
        self.pushButtonParts.setText(_translate("MainWindow", "            Parts"))
        self.pushButtonEngeneer.setText(_translate("MainWindow", "Maintenance"))
        self.pushButtonOperator.setText(_translate("MainWindow", "               Operator"))
        self.pushButtonInput.setText(_translate("MainWindow", "           Incoming"))
        self.pushButtonStok.setText(_translate("MainWindow", "      Outgoing"))
        self.pushButtonEquipment.setText(_translate("MainWindow", "         Equipment"))
        self.pushButton_Incoming_Back.setText(_translate("MainWindow", "<-"))
        self.label_SPN.setText(_translate("MainWindow", "SPN"))
        self.label_DPN.setText(_translate("MainWindow", "DPN"))
        self.label_Invoice_Number.setText(_translate("MainWindow", "Invoice Number"))
        self.label_QTY.setText(_translate("MainWindow", "QTY"))
        self.label_Description.setText(_translate("MainWindow", "Description"))
        self.label_Store_place.setText(_translate("MainWindow", "Store Place"))
        self.label_Price.setText(_translate("MainWindow", "Price"))
        self.label_Date_Order.setText(_translate("MainWindow", "Date Order"))
        self.label_Date_Incoming.setText(_translate("MainWindow", "Date Incoming"))
        self.dateTimeEdit_Date_Order.setDisplayFormat(_translate("MainWindow", "yyyy/M/d h:mm AP"))
        self.dateEdit_Date_Incoming.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.groupBox_Incoming.setTitle(_translate("MainWindow", "Type of Detail"))
        self.radioButton_Incoming_SP.setText(_translate("MainWindow", "Spare Parts"))
        self.radioButton_Incoming_WP.setText(_translate("MainWindow", "Wearing Parts"))
        self.pushButton_Parts_Back.setText(_translate("MainWindow", "<-"))
        self.label_SAP_NUMBER.setText(_translate("MainWindow", "SAP NUMBER"))
        self.label_Parts_Projects.setText(_translate("MainWindow", "PROJECT"))
        self.groupBox_Parts_MaxMin.setTitle(_translate("MainWindow", "MAXandMIN"))
        self.label_Parts_Max.setText(_translate("MainWindow", "MAX"))
        self.label_Parts_Min.setText(_translate("MainWindow", "MIN"))
        self.groupBox_Parts_Search_Type.setTitle(_translate("MainWindow", "Search Type"))
        self.radioButton_Parts_DPN.setText(_translate("MainWindow", "DPN"))
        self.radioButton_Parts_Description.setText(_translate("MainWindow", "Description"))
        self.groupBox_Parts_Building.setTitle(_translate("MainWindow", "Building"))
        self.radioButton_Parts_MQB1.setText(_translate("MainWindow", "MQB1"))
        self.radioButton_Parts_MQB2.setText(_translate("MainWindow", "MQB2"))
        self.radioButton_EQIUPMENT_MQB1.setText(_translate("MainWindow", "MQB1"))
        self.label_Serial_number.setText(_translate("MainWindow", "Serial Number"))
        self.radioButton_EQIUPMENT_MQB2.setText(_translate("MainWindow", "MQB2"))
        self.pushButton_EQUIPMENT_Back.setText(_translate("MainWindow", "<-"))
        self.label_EQP_Description.setText(_translate("MainWindow", "EQP Description"))
        self.label_QS_Number.setText(_translate("MainWindow", "QS Number"))
        self.label_EQIUPMENT_Date.setText(_translate("MainWindow", "Date"))
        self.label_maintenance_Area.setText(_translate("MainWindow", "Area"))
        self.label_maintenance_Name.setText(_translate("MainWindow", "Name"))
        self.pushButton_Maintenance_Back.setText(_translate("MainWindow", "<-"))
        self.label_maintenance_Tab_Numer.setText(_translate("MainWindow", "Tab number"))
        self.pushButton_Operators_Back.setText(_translate("MainWindow", "<-"))
        self.label_operators_Name.setText(_translate("MainWindow", "Name"))
        self.label_operators_Tab_Number.setText(_translate("MainWindow", "Tab Number"))
        self.label_operators_Team.setText(_translate("MainWindow", "Team"))
        self.pushButton_Outgoing_Back.setText(_translate("MainWindow", "<-"))
        self.label_Outgoing_DPN.setText(_translate("MainWindow", "DPN"))
        self.label_Outgoing_Equipment.setText(_translate("MainWindow", "Equipment"))
        self.label_Outgoing_maintenance.setText(_translate("MainWindow", "Maintenance name"))
        self.label_Outgoing_QTY.setText(_translate("MainWindow", "QTY"))
        self.radioButton_Outgoing_MQB2.setText(_translate("MainWindow", "MQB 2"))
        self.radioButton_Outgoing_MQB1.setText(_translate("MainWindow", "MQB 1"))
        self.label_Outgoing_Scan_Key.setText(_translate("MainWindow", "SCAN KEY"))
        self.label_Outgoing_Reason.setText(_translate("MainWindow", "Reason"))
        self.label_Outgoing_Date.setText(_translate("MainWindow", "Date"))
        self.pushButton_Crimping_Die_Back.setText(_translate("MainWindow", "<-"))
        self.groupBox_Crimping_Die.setTitle(_translate("MainWindow", "IncomingOROutgoing"))
        self.radioButton_Crimping_Die__Incomming.setText(_translate("MainWindow", "Incoming"))
        self.radioButton_Crimping_Die_Outgoing.setText(_translate("MainWindow", "Outgoing"))
        self.label_Crimping_Die_Date.setText(_translate("MainWindow", "Date"))
        self.label_Crimping_Die_Crimping_Tool.setText(_translate("MainWindow", "Crimping Tool"))
        self.dateEdit_Crimping_Die_Date.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.label_Crimping_Die_Equipment.setText(_translate("MainWindow", "Equipment"))
        self.label_Crimping_Die_Employee.setText(_translate("MainWindow", "Employee"))
        self.pushButton_Crimping_Maintenance_Back.setText(_translate("MainWindow", "<-"))
        self.groupBox_Crimping_Maintenance.setTitle(_translate("MainWindow", "IncomingOROutgoing"))
        self.radioButton_Crimping_Maintenance_Incomming.setText(_translate("MainWindow", "Incoming for service"))
        self.radioButton_Crimping_Maintenance_Outgoing.setText(_translate("MainWindow", "Outgoing from service"))
        self.label_Crimping_Maintenance_Date.setText(_translate("MainWindow", "Date"))
        self.label_Crimping_Maintenance_Crimping_Tool.setText(_translate("MainWindow", "Crimping Tool"))
        self.dateEdit_Crimping_Maintenance.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.label_Crimping_Maintenance_Employee.setText(_translate("MainWindow", "Maintenance"))
        self.pushButton_Crimping_Terminal_Back.setText(_translate("MainWindow", "<-"))
        self.groupBox_Crimping_Terminal.setTitle(_translate("MainWindow", "IncomingOROutgoing"))
        self.radioButton_Crimping_Terminal_Incoming.setText(_translate("MainWindow", "Incoming"))
        self.radioButton_Crimping_Terminal_Outgoing.setText(_translate("MainWindow", "Outgoing"))
        self.label_Crimping_Terminal_2.setText(_translate("MainWindow", "Date"))
        self.label_Crimping_Terminal_Crimping_Tool.setText(_translate("MainWindow", "Crimping Tool"))
        self.dateEdit_Crimping_Terminal.setDisplayFormat(_translate("MainWindow", "yyyy/M/d"))
        self.label_Crimping_Terminal_Equipment.setText(_translate("MainWindow", "Equipment"))
        self.label_Crimping_Terminal_Employee.setText(_translate("MainWindow", "Employee"))
        self.pushButtonPartsEmploeeReport.setText(_translate("MainWindow", "Запчастини/Людина"))
        self.pushButtonMounthlyStockProduction.setText(_translate("MainWindow", "Місячне Списання Виробництво"))
        self.pushButtonOrderReport.setText(_translate("MainWindow", "Замовлення"))
        self.pushButtonPartsMachineReport.setText(_translate("MainWindow", "Запчастини/Машина"))
        self.pushButtonTimeLifeSP.setText(_translate("MainWindow", "Цикл роботи/використання SP"))
        self.pushButtonStockReport.setText(_translate("MainWindow", "STOCK"))
        self.pushButton_Reports_Back.setText(_translate("MainWindow", "<-"))
        self.pushButtonMounthlyStockCutting.setText(_translate("MainWindow", "Місячне Списання Різка"))
        self.pushButtonDailyReport.setText(_translate("MainWindow", "Щоденний"))
        self.pushButton_Stock_report_excel.setText(_translate("MainWindow", "Export to excel"))
        self.pushButton_Stock_report_Back.setText(_translate("MainWindow", "<-"))
        self.pushButton_Stock_report_refresh.setText(_translate("MainWindow", "Refresh Stock report"))

import res_sp

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

